/* ================================================================ chapter 5
   Consumer Markets and Buyer Behavior. The four sections are the Exam 2 study
   guide's. Each explains its point in plain terms first, then gives the
   concepts behind it; examples stay only where they show a concept at work.   */
var CH = {};
CH.c5 = {n:5, title:"Consumer Markets and Buyer Behavior", short:"Consumers",
 notes:[
  {id:"c5-model", h:"Model of Consumer Behavior", body:
   '<div class="point"><b>The point</b><p>Marketers can see what goes into a purchase — their own product, price, place and promotion, plus the economy, technology and social and cultural forces — and what comes out: what people buy, when, where, how much, and how they feel about the brand. What they cannot see is the middle, the buyer’s characteristics and decision process, so the model calls it a black box. The rest of chapter 5 is about opening that box.</p><p class="able"><b>Be able to</b> place any stimulus or response in Figure 5.1, and explain why the black box matters to marketers.</p></div>'+
   '<p><b>Consumer buyer behavior</b> is the buying behavior of final consumers — individuals and households that buy goods and services for personal consumption. <b>Consumer markets</b> are made up of all those individuals and households.</p>'+
   '<p>Companies research what consumers buy, where, how, how much, when — and <i>why</i>. The whats and wheres can be measured; the whys are locked in the consumer’s mind, and often consumers themselves don’t know.</p>'+
   '<div class="quote">How do consumers respond to various marketing efforts the company might use?<small>The central question for marketers</small></div>'+
   '<h3>Figure 5.1 · The model of buyer behavior</h3>'+
   '<div class="flow"><div class="step"><b>The environment</b>Marketing stimuli: product, price, place, promotion. Other stimuli: economic, technological, social, cultural.</div>'+
   '<div class="step"><b>Buyer’s black box</b>Buyer’s characteristics; buyer’s decision process.</div>'+
   '<div class="step"><b>Buyer responses</b>Buying attitudes and preferences; purchase behavior — what, when, where, how much; brand engagements and relationships.</div></div>'+
   '<div class="exam-tip"><b>Why “black box”</b>Stimuli go in and responses come out, but you can’t see inside. Marketers spend a lot of energy and money trying to figure out what makes customers tick — the characteristics (next section) and the decision process (the section after).</div>'},
  {id:"c5-chars", h:"Characteristics Affecting Consumer Behavior", body:
   '<div class="point"><b>The point</b><p>Four groups of characteristics shape what a person buys: <b>cultural</b> (the values learned from society, a subculture, a social class), <b>social</b> (groups, family, roles and status), <b>personal</b> (age, occupation, income, lifestyle, personality) and <b>psychological</b> (motivation, perception, learning, beliefs and attitudes). Marketers cannot control these, but they must understand them to predict how buyers will respond.</p><p class="able"><b>Be able to</b> name the four groups and what belongs in each, and — given a buying story — say which factor is at work and why.</p></div>'+
   '<h3 class="sub" id="c5-factors">Figure 5.2 · The four factors</h3>'+
   '<p class="knowline"><span class="know">Objective 5.2 — name the four</span></p>'+
   '<p>Consumer purchases are influenced strongly by cultural, social, personal and psychological characteristics. For the most part marketers cannot control these factors, but they must take them into account.</p>'+
   '<div class="boxrow four"><div class="box"><h4>Cultural</h4><ul><li>Culture</li><li>Subculture</li><li>Social class</li></ul></div>'+
   '<div class="box"><h4>Social</h4><ul><li>Groups and social networks</li><li>Family</li><li>Roles and status</li></ul></div>'+
   '<div class="box"><h4>Personal</h4><ul><li>Age and life-cycle stage</li><li>Occupation</li><li>Economic situation</li><li>Lifestyle</li><li>Personality and self-concept</li></ul></div>'+
   '<div class="box"><h4>Psychological</h4><ul><li>Motivation</li><li>Perception</li><li>Learning</li><li>Beliefs and attitudes</li></ul></div></div>'+
   '<p class="ask">A good self-test: what factors influenced your decision to buy the specific smartphone you have? Try to name one from each group.</p>'+
   '<h3 class="sub" id="c5-cultural">Cultural factors</h3>'+
   '<h3>Culture</h3>'+
   '<p><b>Culture</b> is the set of basic values, perceptions, wants and behaviors learned by a member of society from family and other important institutions. It exerts the broadest and deepest influence. Marketers are always trying to <b>spot cultural shifts</b> to discover new products that might be wanted — the shift toward health and fitness created a huge industry, and the class’s own examples were the shifts to bottled water, to working mothers, and away from plastic straws.</p>'+
   '<h3>Subculture</h3>'+
   '<p><b>Subcultures</b> are groups of people within a culture with shared value systems based on common life experiences and situations — nationalities, religions, racial groups, geographic regions. Many brands build tailored programs for subcultures such as Hispanic American, African American and Asian American consumers, each with its own needs and buying patterns; <b>cross-cultural marketing</b> instead includes ethnic themes within mainstream marketing, appealing to similarities across subcultures.</p>'+
   '<h3>Social class</h3>'+
   '<p><b>Social classes</b> are society’s relatively permanent and ordered divisions whose members share similar values, interests and behaviors. Class is not measured by a single factor such as income but by a combination — occupation, income, education, wealth and other variables. In some social systems people are reared for certain roles and cannot change positions; in the United States the lines are not fixed and rigid — people can move up or drop down.</p>'+
   '<p>Marketers care because people within a class tend to exhibit similar buying behavior — distinct preferences in clothing, home furnishings, travel and leisure, financial services and automobiles.</p>'+
   '<h3 class="sub" id="c5-social">Social factors</h3>'+
   '<h3>Groups and social networks</h3>'+
   '<ul><li><b>Reference groups</b> serve as direct or indirect points of comparison in forming attitudes and behavior.</li>'+
   '<li><b>Word-of-mouth influence</b> — the personal words of trusted friends and other consumers are more credible than commercial sources.</li>'+
   '<li><b>Opinion leaders</b> — people within a reference group who, because of special skills, knowledge, personality or other characteristics, exert influence on others. Marketers of brands under strong group influence must reach them.</li>'+
   '<li><b>Influencer marketing</b> — enlisting established influencers, or creating new ones, to spread the word about the brand.</li>'+
   '<li><b>Online social networks</b> — marketers work to harness them to promote products and build closer relationships.</li></ul>'+
   '<h3>Family, roles and status</h3>'+
   '<p><b>Family is the most important consumer-buying organization in society.</b> Marketers study the roles and influence of husband, wife and children on different purchases — and the brand parents used often becomes the brand the children buy, as with the family in class whose cars were all Hondas.</p>'+
   '<p>A person belongs to many groups; the position in each is a <b>role</b> (the activities people are expected to perform) carrying a <b>status</b> (the esteem society gives it). People choose products appropriate to their roles and status — the same woman buys differently as a brand manager, as a mother, and as a fan at the game.</p>'+
   '<h3 class="sub" id="c5-personal">Personal factors</h3>'+
   '<ul><li><b>Occupation</b> affects the goods and services bought; companies can specialize in an occupational group (scrubs sold direct to medical professionals).</li>'+
   '<li><b>Age and life-cycle stage</b> — tastes in food, clothes, furniture and recreation change with age and with the stage of family life, so marketers often define segments by life stage rather than age alone.</li>'+
   '<li><b>Economic situation</b> — trends in spending, personal income, savings and interest rates. In frugal times companies redesign, reposition and reprice; a retailer stresses the “pay less” side of its slogan.</li>'+
   '<li><b>Lifestyle</b> is a person’s pattern of living as expressed in <b>psychographics</b> — measuring <b>AIOs</b>: activities, interests, opinions. Consumers don’t just buy products; they buy the values and lifestyles those products represent — KitchenAid sells a cooking and entertaining lifestyle, not just mixers.</li>'+
   '<li><b>Personality</b> — the unique psychological characteristics that distinguish a person or group. Brands have personalities too, and consumers choose brands that match their own. <b>Self-concept</b> (self-image) is the related idea that possessions reflect and contribute to identity — “we are what we consume.”</li></ul>'+
   '<h3>The five brand personality traits</h3>'+
   '<div class="tblwrap"><table class="tbl n0"><thead><tr><th>Trait</th><th>Means</th></tr></thead><tbody>'+
   '<tr><td class="head">Sincerity</td><td class="sm">down-to-earth, honest, wholesome, cheerful</td></tr>'+
   '<tr><td class="head">Excitement</td><td class="sm">daring, spirited, imaginative, up-to-date</td></tr>'+
   '<tr><td class="head">Competence</td><td class="sm">reliable, intelligent, successful</td></tr>'+
   '<tr><td class="head">Sophistication</td><td class="sm">upper class, charming</td></tr>'+
   '<tr><td class="head">Ruggedness</td><td class="sm">outdoorsy, tough</td></tr>'+
   '</tbody></table></div>'+
   '<p class="ask">Self-test: pick five car brands and assign each a trait. The point is not the “right” brand — it is that buyers read a personality into a brand and choose the one that fits their own.</p>'+
   '<h3 class="sub" id="c5-psych">Psychological factors</h3>'+
   '<h3>Motivation</h3>'+
   '<p>A <b>motive</b> (or drive) is a need that is sufficiently pressing to direct the person to seek satisfaction. <b>Motivation research</b> is qualitative research designed to probe consumers’ hidden, subconscious motivations — depth interviews, describing brands as animals or cars — because people often cannot say why they buy.</p>'+
   '<h3>Figure 5.3 · Maslow’s hierarchy of needs</h3>'+
   '<p>Human needs are arranged in a hierarchy from the most pressing to the least. A person tries to satisfy the most important need first; once satisfied it stops being a motivator, and the next need takes over. Starving people take little interest in the art world.</p>'+
   '<div class="levels">'+
   '<div class="lv"><b>5 · Self-actualization</b><span>self-development and realization</span></div>'+
   '<div class="lv"><b>4 · Esteem needs</b><span>self-esteem, recognition, status</span></div>'+
   '<div class="lv"><b>3 · Social needs</b><span>sense of belonging, love</span></div>'+
   '<div class="lv"><b>2 · Safety needs</b><span>security, protection</span></div>'+
   '<div class="lv"><b>1 · Physiological needs</b><span>hunger, thirst</span></div></div>'+
   '<h3>Perception</h3>'+
   '<p><b>Perception</b> is the process by which people select, organize and interpret information to form a meaningful picture of the world. Two people with the same motive in the same situation can act differently because they perceive it differently. Three perceptual processes explain why: <b>selective attention</b> (people screen out most of the stimuli they are exposed to), <b>selective distortion</b> (they interpret information to fit what they already believe) and <b>selective retention</b> (they remember what supports their attitudes and forget the rest). Marketers therefore have to work hard just to get a message noticed, understood and remembered.</p>'+
   '<h3>Learning</h3>'+
   '<p><b>Learning</b> is the change in behavior arising from experience. It occurs through the interplay of <b>drives, stimuli, cues, responses and reinforcement</b>. A drive is a strong internal stimulus calling for action; it becomes a motive when directed toward a stimulus object (a camera). Cues are minor stimuli that determine when, where and how the person responds (brands in a window, a sale price, a friend’s advice). If buying the Nikon is rewarding, the response is reinforced — next time the odds of buying Nikon are higher.</p>'+
   '<h3>Beliefs and attitudes</h3>'+
   '<p>Through doing and learning, people acquire beliefs and attitudes, which in turn influence their buying. A <b>belief</b> is a descriptive thought a person holds about something (“this brand lasts longer”); beliefs make up product and brand images, and marketers correct the wrong ones. An <b>attitude</b> is a person’s consistently favorable or unfavorable evaluations, feelings and tendencies toward an object or idea. Attitudes are hard to change — they fit into a pattern — so a company usually does better fitting its products into existing attitudes than trying to change them.</p>'+
   '<div class="exam-tip"><b>The practical significance for marketers</b>Build demand by associating the product with strong drives, using motivating cues, providing positive reinforcement, getting past selective attention, and fitting the product to existing beliefs and attitudes.</div>'},
  {id:"c5-decide", h:"Buying Decision Behavior and The Buyer Decision Process", body:
   '<div class="point"><b>The point</b><p>How carefully someone buys depends on how <b>involved</b> she is and how <b>different the brands</b> look to her — that gives four types of buying behavior. When she does decide, she moves through five stages — recognizing a need, searching, evaluating, buying, and living with the purchase — and marketers can influence each one.</p><p class="able"><b>Be able to</b> classify a purchase into one of the four types, name the stage a shopper is in, and explain what cognitive dissonance is and what marketers do about it.</p></div>'+
   '<h3 class="sub" id="c5-types">Figure 5.4 · The four types of buying decision behavior</h3>'+
   '<p class="knowline"><span class="know">Objective 5.3</span></p>'+
   '<p>Buying differs for toothpaste, a smartphone, financial services and a new car. Two variables sort it: the buyer’s <b>involvement</b> (how much the purchase matters and how much it costs or risks) and the <b>differences between brands</b> (how different the choices look to the buyer).</p>'+
   '<div class="matrix"><div class="mx-corner"></div><div class="mx-h">Significant differences between brands</div><div class="mx-h">Few differences between brands</div>'+
   '<div class="mx-v">High involvement</div>'+
   '<div class="mx-c"><span class="lab">High involvement · significant differences</span><h4>Complex buying behavior</h4>The product is expensive, risky, purchased infrequently and highly self-expressive. The buyer must learn a great deal, goes through a learning process and makes a thoughtful choice.<i>A new car.</i></div>'+
   '<div class="mx-c"><span class="lab">High involvement · few differences</span><h4>Dissonance-reducing buying behavior</h4>Expensive, infrequent, risky — but the buyer sees little difference among brands, so may buy fairly quickly, responding to price or convenience, and feel dissonance afterward.<i>Carpeting.</i></div>'+
   '<div class="mx-v">Low involvement</div>'+
   '<div class="mx-c"><span class="lab">Low involvement · significant differences</span><h4>Variety-seeking buying behavior</h4>Low cost, not risky, bought often; the buyer switches brands just to try something different, not out of dissatisfaction. Market leaders dominate shelf space; challengers use lower prices, free samples and advertising.<i>Cookies.</i></div>'+
   '<div class="mx-c"><span class="lab">Low involvement · few differences</span><h4>Habitual buying behavior</h4>Low cost, frequent, not self-expressive; the buyer picks a familiar brand out of habit, not loyalty, and may respond to price or a coupon.<i>Salt — what brand of salt do you buy, and why?</i></div></div>'+
   '<h3 class="sub" id="c5-process">Figure 5.5 · The buyer decision process</h3>'+
   '<p class="knowline"><span class="know">The five stages</span></p>'+
   '<p>The buying process starts long before the actual purchase and continues long after — it may even end in a decision not to buy. Buyers may pass quickly or slowly, and in routine purchases skip or reverse stages. Marketers must focus on the entire process, not just the purchase decision.</p>'+
   '<div class="flow">'+
   '<div class="step"><b>1 · Need recognition</b>The consumer recognizes a problem or need, triggered by <b>internal</b> stimuli (hunger) or <b>external</b> stimuli (an ad, a friend). Marketers research what needs arise and how they led to the product.</div>'+
   '<div class="step"><b>2 · Information search</b>If the drive is strong and a satisfying product is at hand, the consumer buys; otherwise the need is stored or a search begins. Sources: <b>personal, commercial, public, experiential</b>. Commercial sources inform; personal sources legitimize or evaluate.</div>'+
   '<div class="step"><b>3 · Evaluation of alternatives</b>The consumer uses information to evaluate brands in the choice set — careful calculation, intuition or impulse, depending on the person and the situation.</div>'+
   '<div class="step"><b>4 · Purchase decision</b>Usually the most preferred brand — but purchase intention isn’t purchase decision: <b>attitudes of others</b> and <b>unexpected situational factors</b> get in the way.</div>'+
   '<div class="step"><b>5 · Postpurchase behavior</b>Satisfaction depends on the gap between <b>expectations</b> and <b>perceived performance</b>: fall short and the customer is disappointed, meet them and she is satisfied, exceed them and she is delighted. Marketers aim not just to meet expectations but to delight.</div></div>'+
   '<p><b>Cognitive dissonance</b> is buyer discomfort caused by postpurchase conflict. Consumers feel at least some dissonance after every major purchase — glad for the chosen brand’s benefits, uneasy about its drawbacks and the benefits of the brands not bought. Marketers should alleviate it by reinforcing the chosen brand’s benefits, because a satisfied customer buys again and tells others, and a dissatisfied one tells even more people.</p>'+
   '<p>The <b>customer journey</b> is the sum of the ongoing experiences consumers have with a brand that affect their buying behavior, engagement and advocacy over time; understanding it lets marketers create experiences that lead to positive purchase, engagement and advocacy.</p>'},
  {id:"c5-newprod", h:"The Buyer Decision Process for New Products", body:
   '<div class="point"><b>The point</b><p>For something new, buyers go from first hearing of it to regular use in five steps, some people much sooner than others (innovators first, laggards last), and the product’s own traits — how much better it is, how well it fits, how simple it is, how easy it is to try and to see working — decide how fast it spreads.</p><p class="able"><b>Be able to</b> order the adoption stages, describe each adopter group, and say which product characteristic a marketing move is improving.</p></div>'+
   '<h3 class="sub" id="c5-adoption">The adoption process</h3>'+
   '<p class="knowline"><span class="know">Objective 5.4</span></p>'+
   '<p>A <b>new product</b> is a good, service or idea perceived by some potential customers as new. The <b>adoption process</b> is the mental process an individual goes through from first learning about an innovation to final regular use.</p>'+
   '<div class="flow"><div class="step"><b>Awareness</b>Aware of the product but lacking information.</div><div class="step"><b>Interest</b>Seeks information.</div><div class="step"><b>Evaluation</b>Considers whether trying it makes sense.</div><div class="step"><b>Trial</b>Tries it on a small scale to estimate its value.</div><div class="step"><b>Adoption</b>Decides on full and regular use.</div></div>'+
   '<p>Marketers help buyers along: if consumers don’t perceive a need, advertising can trigger it; if they know the product but hold unfavorable attitudes, change the product or the perceptions; if they hesitate to try, offer a sample or a trial.</p>'+
   '<h3 class="sub" id="c5-adopters">Figure 5.6 · Adopter categories by time of adoption</h3>'+
   '<p>People differ in how ready they are to try new products. The shares below are the textbook’s; the class described who tends to fall in each group.</p>'+
   '<div class="exam-tip"><b>Two namings</b>The slide writes “Early <b>majority</b>/mainstream” and “Later majority/mainstream,” and the last group is <b>laggards</b> or lagging adopters. Majority and mainstream are the same group — recognise either.</div>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th>Group</th><th>Share</th><th>Value</th><th>Who they tend to be</th></tr></thead><tbody>'+
   '<tr><td class="head">Innovators</td><td class="num">2.5%</td><td class="sm"><b>Venturesome</b> — try new ideas at some risk.</td><td class="sm">Risk takers, often affluent, close to the technology behind the product.</td></tr>'+
   '<tr><td class="head">Early adopters</td><td class="num">13.5%</td><td class="sm">Guided by <b>respect</b> — opinion leaders who adopt early but carefully.</td><td class="sm">The most influential group — “thought leaders,” high social status, active in social media.</td></tr>'+
   '<tr><td class="head">Early majority / early mainstream</td><td class="num">34%</td><td class="sm"><b>Deliberate</b> — rarely leaders, but adopt before the average person.</td><td class="sm">Risk averse, above-average status, in contact with the thought leaders.</td></tr>'+
   '<tr><td class="head">Late majority / late mainstream</td><td class="num">34%</td><td class="sm"><b>Skeptical</b> — adopt only after a majority has tried it.</td><td class="sm">Risk averse, less contact with thought leaders, less money to risk.</td></tr>'+
   '<tr><td class="head">Laggards / lagging adopters</td><td class="num">16%</td><td class="sm"><b>Tradition bound</b> — suspicious of change; adopt when it has become a tradition itself.</td><td class="sm">Highly change averse; their arrival signals the product is starting to decline.</td></tr>'+
   '</tbody></table></div>'+
   '<p class="ask">The professor’s slide lists lagging adopters at 10%; Figure 5.6 and the arithmetic (2.5 + 13.5 + 34 + 34 + 16 = 100) say 16%. Use 16% unless he says otherwise.</p>'+
   '<p>New-product marketers target innovators and early adopters first, because they in turn influence the later adopters.</p>'+
   '<h3 class="sub" id="c5-rate">Characteristics that affect the rate of adoption</h3>'+
   '<div class="exam-tip"><b>Two names for the last two</b>The class notes call them <b>divisibility</b> and <b>communicability</b>; the slides and the textbook call the same two <b>trialability</b> and <b>observability</b>. Same definitions — recognise either.</div>'+
   '<ul><li><b>Relative advantage</b> — the degree to which the innovation appears superior to existing products. The bigger the advantage, the faster the adoption.</li><li><b>Compatibility</b> — how well it fits the values and experiences of potential consumers.</li><li><b>Complexity</b> — how difficult it is to understand or use; the harder, the slower.</li><li><b>Trialability</b>, in the class notes <b>divisibility</b> — whether it can be tried on a limited basis.</li><li><b>Observability</b>, in the class notes <b>communicability</b> — whether the results can be observed or described to others.</li></ul>'+
   '<p>Also: initial and ongoing costs, risk and uncertainty, social approval. Marketers study all of these when developing and marketing a new product.</p>'}
 ],
 decks:[
  {id:"terms", label:"Key terms", cards:[
   ["Consumer buyer behavior","The buying behavior of final consumers — individuals and households buying for personal consumption","g5-model"],
   ["Consumer market","All the individuals and households that buy or acquire goods and services for personal consumption","g5-model"],
   ["Buyer’s black box","The buyer’s characteristics and decision process — stimuli go in, responses come out, and marketers can’t see inside","g5-model"],
   ["Culture","The set of basic values, perceptions, wants and behaviors learned by a member of society from family and other institutions","g5-chars"],
   ["Subculture","A group within a culture with a shared value system based on common life experiences and situations","g5-chars"],
   ["Social class","Society’s relatively permanent and ordered divisions whose members share similar values, interests and behaviors","g5-chars"],
   ["Cross-cultural marketing","Including ethnic themes and cross-cultural perspectives within mainstream marketing","g5-chars"],
   ["Reference group","A group that serves as a direct or indirect point of comparison in forming attitudes and behavior","g5-chars"],
   ["Opinion leader","A person within a reference group who, because of special skills, knowledge or personality, exerts influence on others","g5-chars"],
   ["Word-of-mouth influence","Personal recommendations of trusted friends and other consumers — more credible than commercial sources","g5-chars"],
   ["Influencer marketing","Enlisting established influencers or creating new ones to spread the word about a brand","g5-chars"],
   ["Role","The activities people are expected to perform according to the people around them","g5-chars"],
   ["Status","The general esteem society gives to a role","g5-chars"],
   ["Lifestyle","A person’s pattern of living as expressed in his or her psychographics","g5-chars"],
   ["Psychographics","Measuring a consumer’s AIOs — activities, interests, opinions","g5-chars"],
   ["Personality","The unique psychological characteristics that distinguish a person or group","g5-chars"],
   ["Brand personality","The specific mix of human traits that may be attributed to a particular brand","g5-chars"],
   ["Motive (drive)","A need that is sufficiently pressing to direct the person to seek satisfaction","g5-chars"],
   ["Motivation research","Qualitative research designed to probe consumers’ hidden, subconscious motivations","g5-chars"],
   ["Perception","The process by which people select, organize and interpret information to form a meaningful picture of the world","g5-chars"],
   ["Learning","Changes in behavior arising from experience — through drives, stimuli, cues, responses and reinforcement","g5-chars"],
   ["Cue","A minor stimulus that determines when, where and how a person responds","g5-chars"],
   ["Belief","A descriptive thought a person holds about something","g5-chars"],
   ["Attitude","A person’s consistently favorable or unfavorable evaluations, feelings and tendencies toward an object or idea","g5-chars"],
   ["Complex buying behavior","High involvement, significant brand differences — an expensive, risky, self-expressive purchase","g5-decide"],
   ["Dissonance-reducing buying behavior","High involvement but few perceived brand differences","g5-decide"],
   ["Habitual buying behavior","Low involvement, few brand differences — a familiar brand bought out of habit","g5-decide"],
   ["Variety-seeking buying behavior","Low involvement, significant brand differences — switching just to try something different","g5-decide"],
   ["Need recognition","The first stage: the consumer recognizes a problem or need from internal or external stimuli","g5-decide"],
   ["Information search","The stage in which the consumer is motivated to search for more information","g5-decide"],
   ["Alternative evaluation","The stage in which the consumer uses information to evaluate brands in the choice set","g5-decide"],
   ["Purchase decision","The buyer’s decision about which brand to purchase","g5-decide"],
   ["Postpurchase behavior","Further action after purchase, based on satisfaction or dissatisfaction","g5-decide"],
   ["Cognitive dissonance","Buyer discomfort caused by postpurchase conflict","g5-decide"],
   ["Customer journey","The sum of ongoing experiences with a brand that affect buying, engagement and advocacy over time","g5-decide"],
   ["New product","A good, service or idea perceived by some potential customers as new","g5-newprod"],
   ["Adoption process","The mental process from first learning about an innovation to final regular use","g5-newprod"]]},
  {id:"lists", label:"Lists & frameworks", cards:[
   ["The four factors","Cultural, social, personal, psychological","g5-chars"],
   ["Cultural factors","Culture, subculture, social class","g5-chars"],
   ["Social factors","Groups and social networks, family, roles and status","g5-chars"],
   ["Personal factors","Age and life-cycle stage, occupation, economic situation, lifestyle, personality and self-concept","g5-chars"],
   ["Psychological factors","Motivation, perception, learning, beliefs and attitudes","g5-chars"],
   ["Maslow, bottom to top","Physiological, safety, social, esteem, self-actualization","g5-chars"],
   ["The three perceptual processes","Selective attention, selective distortion, selective retention","g5-chars"],
   ["Five brand personality traits","Sincerity, excitement, competence, sophistication, ruggedness","g5-chars"],
   ["The most important consumer-buying organization","The family","g5-chars"],
   ["The two variables behind the four types of buying behavior","Involvement (high or low) and differences between brands (significant or few)","g5-decide"],
   ["The five stages of the buyer decision process","Need recognition, information search, evaluation of alternatives, purchase decision, postpurchase behavior","g5-decide"],
   ["The four information sources","Personal, commercial, public, experiential","g5-decide"],
   ["What blocks intention from becoming purchase","Attitudes of others; unexpected situational factors","g5-decide"],
   ["What determines postpurchase satisfaction","The relationship between expectations and perceived performance","g5-decide"],
   ["The five stages of adoption","Awareness, interest, evaluation, trial, adoption","g5-newprod"],
   ["Adopter shares","Innovators 2.5%, early adopters 13.5%, early mainstream 34%, late mainstream 34%, lagging adopters 16%","g5-newprod"],
   ["Adopter values","Venturesome, respect, deliberate, skeptical, tradition bound","g5-newprod"],
   ["Five characteristics of the rate of adoption","Relative advantage, compatibility, complexity, trialability, observability","g5-newprod"],
   ["The class notes’ names for the last two","Divisibility = trialability (tried on a limited basis); communicability = observability (results can be seen or described)","g5-newprod"],
   ["Adopter categories, both namings","Innovators · early adopters · early majority (early mainstream) · late majority (late mainstream) · laggards (lagging adopters)","g5-newprod"]]}
 ]
};

/* ---- chapter 5 questions: the concepts under each heading, and how to apply them ---- */
var QB = [
 {tp:"c5",sec:"g5-model",t:"mc",q:"Consumer buyer behavior refers to the buying behavior of:",a:"final consumers — individuals and households buying for personal consumption",w:["organizations buying for resale","wholesalers and retailers","governments and institutions"],e:"Final consumers. Organizations are chapter 6."},
 {tp:"c5",sec:"g5-model",t:"mc",q:"Consumer markets consist of:",a:"all the individuals and households that buy goods and services for personal consumption",w:["all the organizations that buy goods to resell","all the retailers in a country","everyone who could possibly be reached by advertising"],e:"Consumer markets — the people whose buying behavior chapter 5 is about."},
 {tp:"c5",sec:"g5-model",t:"mc",q:"In the model of buyer behavior, the “black box” contains:",a:"the buyer’s characteristics and decision process",w:["the four Ps","economic and cultural stimuli","purchase behavior and brand engagement"],e:"Stimuli enter the black box (characteristics + decision process) and produce responses."},
 {tp:"c5",sec:"g5-model",t:"mc",q:"Why does the model call the buyer’s mind a “black box”?",a:"Stimuli and responses can be observed, but what happens inside the buyer cannot",w:["Consumers refuse to answer surveys","It applies only to online buying","Marketers are not allowed to study it"],e:"Marketers can measure what goes in and what comes out; the characteristics and decision process in between have to be inferred."},
 {tp:"c5",sec:"g5-model",t:"mc",q:"The central question chapter 5 sets out to answer is:",a:"How do consumers respond to the various marketing efforts the company might use?",w:["How should a company price its products?","Which segments should a company enter?","How is a brand valued financially?"],e:"The whole chapter exists to answer it — and the answer lies inside the black box."},
 {tp:"c5",sec:"g5-model",t:"mc",q:"In Figure 5.1, which of these is a buyer response?",a:"Purchase behavior — what, when, where and how much",w:["The buyer’s decision process","Marketing stimuli","The buyer’s characteristics"],e:"Responses: buying attitudes and preferences; purchase behavior; brand engagements and relationships."},
 {tp:"c5",sec:"g5-model",ap:true,t:"mc",q:"A company cuts its price and sales rise, but nobody can explain why buyers reacted the way they did. The part of Figure 5.1 the company cannot see is:",a:"the buyer’s black box — characteristics and decision process",w:["the marketing stimuli","the buyer responses","the other stimuli"],e:"The price cut is a stimulus it controls; the sales are a response it can measure; the reason lies in the black box."},
 {tp:"c5",sec:"g5-model",t:"tf",q:"Marketers can measure the whats, wheres and whens of consumer buying, but the whys are hard to see.",a:true,e:"True — that is why it is called the black box."},

 {tp:"c5",sec:"g5-chars",t:"mc",q:"Which of these is NOT one of the four major factors influencing consumer behavior?",a:"Economic",w:["Cultural","Social","Psychological"],e:"Cultural, social, personal, psychological. Economic situation is a personal factor, not one of the four."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"The set of basic values, perceptions, wants and behaviors learned from family and other institutions is:",a:"culture",w:["subculture","social class","lifestyle"],e:"Culture."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"Groups within a culture with shared value systems based on common life experiences are:",a:"subcultures",w:["reference groups","social classes","opinion leaders"],e:"Subcultures — nationalities, religions, racial groups, regions."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"Marketers try to spot cultural shifts in order to:",a:"discover new products that might be wanted",w:["change consumers’ basic values","avoid selling to subcultures","control the cultural factor"],e:"The shift toward health and fitness created a huge industry; so did the shift to bottled water."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"Society’s relatively permanent and ordered divisions whose members share similar values, interests and behaviors are:",a:"social classes",w:["subcultures","reference groups","life-cycle stages"],e:"Social classes. In the U.S. the lines are not fixed — people can move."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"Social class is measured by:",a:"a combination of occupation, income, education, wealth and other variables",w:["income alone","the neighborhood a person lives in","the brands a person buys"],e:"Not a single factor but a combination."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"Why do marketers care about social class?",a:"People within a class tend to show similar buying behavior",w:["Class determines income exactly","Classes never change","Only the upper class buys brands"],e:"Similar preferences in clothing, furnishings, travel, financial services and cars."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"What is the difference between a subculture and a social class?",a:"A subculture is based on shared life experiences such as nationality or religion; a social class is an ordered division of society based on occupation, income, education and wealth",w:["A subculture is a personal factor; a social class is a social factor","They are the same thing","A social class is always smaller than a subculture"],e:"Both are cultural factors, but they group people on different things."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"People within a reference group who exert influence because of special skills, knowledge or personality are:",a:"opinion leaders",w:["gatekeepers","early majority","brand ambassadors"],e:"Opinion leaders."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"The most important consumer-buying organization in society is:",a:"the family",w:["the reference group","the social class","the online social network"],e:"The family."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"Psychographics measure a consumer’s AIOs, which stand for:",a:"activities, interests, opinions",w:["age, income, occupation","attitudes, intentions, outcomes","awareness, interest, ownership"],e:"Activities, interests and opinions — the measure of lifestyle."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"The specific mix of human traits attributed to a particular brand is its:",a:"brand personality",w:["brand equity","brand position","brand image"],e:"Brand personality — five traits: sincerity, excitement, competence, sophistication, ruggedness."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"A need that is sufficiently pressing to direct a person to seek satisfaction is a:",a:"motive",w:["cue","belief","stimulus"],e:"A motive, or drive."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"In Maslow’s hierarchy, which need is the most pressing?",a:"Physiological",w:["Safety","Social","Esteem"],e:"Physiological (hunger, thirst) sits at the bottom; self-actualization at the top."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"Perception is:",a:"the process by which people select, organize and interpret information to form a meaningful picture of the world",w:["a need pressing enough to direct a person to act","a change in behavior arising from experience","the esteem society gives to a role"],e:"Perception — and it works through selective attention, distortion and retention."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"Learning occurs through the interplay of:",a:"drives, stimuli, cues, responses and reinforcement",w:["needs, wants and demands","attention, distortion and retention","awareness, interest, evaluation, trial, adoption"],e:"Drives, stimuli, cues, responses, reinforcement."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"Minor stimuli that determine when, where and how a person responds are:",a:"cues",w:["drives","motives","reinforcements"],e:"Cues — several camera brands in a window, a sale price, a friend’s comment."},
 {tp:"c5",sec:"g5-chars",t:"mc",q:"An attitude is:",a:"a person’s consistently favorable or unfavorable evaluations, feelings and tendencies toward an object or idea",w:["a descriptive thought a person holds about something","a minor stimulus that triggers a response","a group used as a point of comparison"],e:"An attitude; the descriptive thought is a belief."},
 {tp:"c5",sec:"g5-chars",ap:true,t:"mc",q:"A family buys a Honda because the parents always drove Hondas. Which factor is at work?",a:"Family — a social factor",w:["Occupation — a personal factor","Learning — a psychological factor","Subculture — a cultural factor"],e:"The brand parents used becomes the brand the children buy."},
 {tp:"c5",sec:"g5-chars",ap:true,t:"mc",q:"A working mother buys a tailored blazer for the office and a team jersey for the game. Which concept explains this?",a:"Roles and status",w:["Social class","Cognitive dissonance","Selective retention"],e:"People choose products appropriate to their roles and status."},
 {tp:"c5",sec:"g5-chars",ap:true,t:"mc",q:"A teenager insists on the sneakers her favorite athlete wears. Which social factor is most at work?",a:"Reference groups and opinion leaders",w:["Social class","Economic situation","Learning"],e:"The athlete is an opinion leader in a reference group the teenager compares herself to."},
 {tp:"c5",sec:"g5-chars",ap:true,t:"mc",q:"After retiring, a couple trades their sports car for a comfortable sedan. Which personal factor explains the change?",a:"Age and life-cycle stage",w:["Subculture","Motivation","Roles and status"],e:"Tastes change with age and stage of life."},
 {tp:"c5",sec:"g5-chars",ap:true,t:"mc",q:"During a downturn, a retailer shifts its advertising to stress low prices. Which personal factor is it responding to?",a:"Economic situation",w:["Lifestyle","Culture","Personality"],e:"In frugal times companies redesign, reposition and reprice."},
 {tp:"c5",sec:"g5-chars",ap:true,t:"mc",q:"KitchenAid sells “an entire cooking and entertainment lifestyle,” not just mixers. Which personal factor does that target?",a:"Lifestyle",w:["Occupation","Economic situation","Age and life-cycle stage"],e:"Lifestyle — consumers buy the values and lifestyles products represent."},
 {tp:"c5",sec:"g5-chars",ap:true,t:"mc",q:"A brand advertises itself as outdoorsy and tough. Which brand personality trait is it projecting?",a:"Ruggedness",w:["Sincerity","Sophistication","Competence"],e:"Ruggedness — outdoorsy, tough. Sincerity is down-to-earth; competence is reliable; sophistication is upper class."},
 {tp:"c5",sec:"g5-chars",ap:true,t:"mc",q:"A hungry traveler stops at the first diner she sees. In Maslow’s terms she is satisfying a:",a:"physiological need",w:["safety need","esteem need","self-actualization need"],e:"Hunger is the most pressing level; the others wait."},
 {tp:"c5",sec:"g5-chars",ap:true,t:"mc",q:"A shopper notices only the ads for the phone she already wants and ignores the rest. This is:",a:"selective attention — part of perception",w:["cognitive dissonance","variety seeking","a cue"],e:"People screen out most stimuli; marketers work hard just to be noticed."},
 {tp:"c5",sec:"g5-chars",ap:true,t:"mc",q:"Because her last Nikon worked well, a photographer buys Nikon again without considering other brands. Which psychological factor is at work?",a:"Learning — the earlier purchase was reinforced",w:["Perception","Motivation research","Subculture"],e:"A rewarding response is reinforced, so the same response is more likely next time."},
 {tp:"c5",sec:"g5-chars",t:"tf",q:"For the most part, marketers can control the cultural, social, personal and psychological factors that shape buying.",a:false,e:"False — they cannot control them, but must take them into account."},
 {tp:"c5",sec:"g5-chars",t:"tf",q:"In the United States, the lines between social classes are fixed and rigid.",a:false,e:"False — people can move to a higher class or drop to a lower one."},
 {tp:"c5",sec:"g5-chars",t:"tf",q:"Word-of-mouth from trusted friends tends to be more credible than advertising.",a:true,e:"True — commercial sources inform, but personal sources legitimise. That is why marketers work to reach opinion leaders instead of only buying ads."},
 {tp:"c5",sec:"g5-chars",t:"tf",q:"Once a Maslow need is satisfied, it stops being a motivator.",a:true,e:"True — the person moves to the next most important need."},
 {tp:"c5",sec:"g5-chars",t:"tf",q:"A belief is a descriptive thought a person holds about something; an attitude is an evaluation of it.",a:true,e:"True — beliefs make up product images; attitudes are consistent evaluations and feelings."},
 {tp:"c5",sec:"g5-chars",t:"tf",q:"Attitudes are easy to change, so marketers usually try to change them rather than fit the product to them.",a:false,e:"False — attitudes are hard to change, so companies usually fit products into existing attitudes."},

 {tp:"c5",sec:"g5-decide",t:"mc",q:"Which two variables define the four types of buying decision behavior?",a:"Degree of involvement and degree of differences among brands",w:["Price and frequency of purchase","Age and income","Culture and social class"],e:"Involvement (high/low) × brand differences (significant/few)."},
 {tp:"c5",sec:"g5-decide",t:"mc",q:"High involvement with few perceived differences among brands is:",a:"dissonance-reducing buying behavior",w:["complex buying behavior","habitual buying behavior","variety-seeking buying behavior"],e:"Dissonance-reducing — expensive and risky, but the brands look alike."},
 {tp:"c5",sec:"g5-decide",t:"mc",q:"Low involvement with significant perceived differences among brands is:",a:"variety-seeking buying behavior",w:["habitual buying behavior","complex buying behavior","dissonance-reducing buying behavior"],e:"Variety seeking — switching just to try something different."},
 {tp:"c5",sec:"g5-decide",t:"mc",q:"Which stage of the buyer decision process comes third?",a:"Evaluation of alternatives",w:["Information search","Purchase decision","Need recognition"],e:"Need recognition → information search → evaluation of alternatives → purchase decision → postpurchase behavior."},
 {tp:"c5",sec:"g5-decide",t:"mc",q:"Which information sources normally inform the buyer, while which legitimize or evaluate?",a:"Commercial sources inform; personal sources legitimize",w:["Personal sources inform; commercial sources legitimize","Public sources inform; experiential sources legitimize","Experiential sources inform; public sources legitimize"],e:"Consumers get the most information from commercial sources, but the most effective sources tend to be personal."},
 {tp:"c5",sec:"g5-decide",t:"mc",q:"Two things that can come between purchase intention and purchase decision are:",a:"attitudes of others and unexpected situational factors",w:["price and promotion","culture and subculture","drives and cues"],e:"Attitudes of others; unexpected situational factors."},
 {tp:"c5",sec:"g5-decide",t:"mc",q:"Buyer discomfort caused by postpurchase conflict is:",a:"cognitive dissonance",w:["selective retention","need recognition","variety seeking"],e:"Cognitive dissonance — felt at least a little after every major purchase."},
 {tp:"c5",sec:"g5-decide",t:"mc",q:"What determines whether a buyer is satisfied with a purchase?",a:"The relationship between expectations and the product’s perceived performance",w:["The price paid","The number of alternatives evaluated","The strength of the brand"],e:"Expectations vs. perceived performance."},
 {tp:"c5",sec:"g5-decide",t:"mc",q:"Why should marketers pay attention to the entire buying process rather than just the purchase decision?",a:"Because the process starts long before the purchase and continues long after it",w:["Because consumers always follow all five stages in order","Because only the purchase decision can be influenced","Because the other stages do not exist for routine purchases"],e:"Need recognition comes long before the sale; satisfaction, dissonance and advocacy come after."},
 {tp:"c5",sec:"g5-decide",t:"mc",q:"Which stage do marketers try to influence by reinforcing the benefits of the brand the customer chose?",a:"Postpurchase behavior",w:["Need recognition","Information search","Evaluation of alternatives"],e:"Reinforcing the chosen brand’s benefits reduces cognitive dissonance."},
 {tp:"c5",sec:"g5-decide",t:"mc",q:"The customer journey is:",a:"the sum of the ongoing experiences consumers have with a brand that affect their buying, engagement and advocacy over time",w:["the five stages of a single purchase","the route a product takes from factory to store","the adoption process for a new product"],e:"Understanding it lets marketers create experiences that lead to purchase, engagement and advocacy."},
 {tp:"c5",sec:"g5-decide",ap:true,t:"mc",q:"A student researches laptops for weeks, compares specs, reads reviews and finally buys. This is:",a:"complex buying behavior",w:["habitual buying behavior","variety-seeking buying behavior","dissonance-reducing buying behavior"],e:"High involvement, significant brand differences."},
 {tp:"c5",sec:"g5-decide",ap:true,t:"mc",q:"A couple buys carpeting quickly because the brands all look alike, then worries afterward whether they chose well. This is:",a:"dissonance-reducing buying behavior",w:["complex buying behavior","habitual buying behavior","variety-seeking buying behavior"],e:"High involvement (expensive, infrequent) with few perceived differences — dissonance follows."},
 {tp:"c5",sec:"g5-decide",ap:true,t:"mc",q:"A shopper grabs a different flavor of chips each week just to try something new. This is:",a:"variety-seeking buying behavior",w:["habitual buying behavior","complex buying behavior","dissonance-reducing buying behavior"],e:"Low involvement, significant differences — brand switching without dissatisfaction."},
 {tp:"c5",sec:"g5-decide",ap:true,t:"mc",q:"A shopper reaches for the same brand of salt every week without thinking about it. This is:",a:"habitual buying behavior",w:["complex buying behavior","variety-seeking buying behavior","dissonance-reducing buying behavior"],e:"Low involvement, few differences — habit, not loyalty."},
 {tp:"c5",sec:"g5-decide",ap:true,t:"mc",q:"An ad for a camera makes a hobbyist realize she wants a better one. Which stage is this?",a:"Need recognition, triggered by an external stimulus",w:["Information search","Evaluation of alternatives","Postpurchase behavior"],e:"An ad is an external stimulus for need recognition."},
 {tp:"c5",sec:"g5-decide",ap:true,t:"mc",q:"She asks two friends what they think of the laptops she is choosing between. Which stage is this, and which source?",a:"Information search — a personal source",w:["Evaluation of alternatives — a commercial source","Purchase decision — a public source","Need recognition — an experiential source"],e:"Friends are personal sources, the ones that legitimize and evaluate."},
 {tp:"c5",sec:"g5-decide",ap:true,t:"mc",q:"She had settled on one brand until her husband objected, and she chose another. Which factor came between intention and decision?",a:"Attitudes of others",w:["An unexpected situational factor","Cognitive dissonance","Selective distortion"],e:"Attitudes of others — the first of the two factors that intervene."},
 {tp:"c5",sec:"g5-decide",ap:true,t:"mc",q:"She was ready to buy the car, then lost her job the week before. Which factor came between intention and decision?",a:"An unexpected situational factor",w:["Attitudes of others","Need recognition","Variety seeking"],e:"Unexpected situational factors — the economy, a competitor’s price drop, a job loss."},
 {tp:"c5",sec:"g5-decide",ap:true,t:"mc",q:"After buying a new car, a buyer keeps reading reviews of it to feel sure he chose right. This is:",a:"reducing cognitive dissonance",w:["variety seeking","need recognition","information search before purchase"],e:"Postpurchase dissonance — marketers help by reinforcing the chosen brand’s benefits."},
 {tp:"c5",sec:"g5-decide",ap:true,t:"mc",q:"Her new blender works even better than she expected. According to the model, she is:",a:"delighted — and likely to buy again and tell others",w:["dissatisfied, because expectations were too low","in the information-search stage","experiencing variety seeking"],e:"Performance above expectations delights; below, disappoints; at, satisfies."},
 {tp:"c5",sec:"g5-decide",t:"tf",q:"Habitual buying behavior reflects strong brand loyalty.",a:false,e:"False — it is habit, not loyalty; buyers respond to price or coupons."},
 {tp:"c5",sec:"g5-decide",t:"tf",q:"The buying process may end in a decision not to buy.",a:true,e:"True — the process starts long before the purchase and continues long after it, and a buyer can stop at any stage. That is why marketers work the whole process, not just the moment of sale."},
 {tp:"c5",sec:"g5-decide",t:"tf",q:"Consumers always pass through all five stages of the decision process in order.",a:false,e:"False — in routine purchases they skip or reverse stages."},
 {tp:"c5",sec:"g5-decide",t:"tf",q:"Almost all major purchases result in some cognitive dissonance.",a:true,e:"True — the buyer is glad of the chosen brand’s benefits but uneasy about its drawbacks and about what the rejected brands offered. Marketers reduce it by reinforcing the choice after the sale."},

 {tp:"c5",sec:"g5-newprod",t:"mc",q:"The stages of the adoption process, in order, are:",a:"awareness, interest, evaluation, trial, adoption",w:["interest, awareness, trial, evaluation, adoption","awareness, trial, interest, evaluation, adoption","need, search, evaluation, purchase, review"],e:"Awareness → interest → evaluation → trial → adoption."},
 {tp:"c5",sec:"g5-newprod",t:"mc",q:"In the adoption process, trial means the consumer:",a:"tries the product on a small scale to estimate its value",w:["hears of the product for the first time","decides on full and regular use","seeks information about it"],e:"Trial — on a small scale, before deciding on regular use."},
 {tp:"c5",sec:"g5-newprod",t:"mc",q:"Early adopters make up what share of adopters?",a:"13.5%",w:["2.5%","34%","16%"],e:"Innovators 2.5%, early adopters 13.5%, early and late mainstream 34% each, lagging adopters 16%."},
 {tp:"c5",sec:"g5-newprod",t:"mc",q:"Which adopter group is described as venturesome — willing to try new ideas at some risk?",a:"Innovators",w:["Early adopters","Early mainstream","Lagging adopters"],e:"Innovators. The early adopters are guided by respect."},
 {tp:"c5",sec:"g5-newprod",t:"mc",q:"Which adopter group is described as “guided by respect” — opinion leaders who adopt early but carefully?",a:"Early adopters",w:["Innovators","Early mainstream","Late mainstream"],e:"Early adopters. Innovators are venturesome; the early mainstream deliberate; the late mainstream skeptical; laggards tradition bound."},
 {tp:"c5",sec:"g5-newprod",t:"mc",q:"Why do new-product marketers aim their first efforts at innovators and early adopters?",a:"Because they influence the later adopters",w:["Because they are the largest groups","Because they are the least price sensitive","Because they never abandon a product"],e:"Early adopters are opinion leaders; the mainstream watches them."},
 {tp:"c5",sec:"g5-newprod",t:"mc",q:"The degree to which an innovation may be tried on a limited basis is its:",a:"trialability",w:["observability","compatibility","relative advantage"],e:"Trialability — the class notes call this one divisibility."},
 {tp:"c5",sec:"g5-newprod",t:"mc",q:"In the class notes, the degree to which an innovation may be tried on a limited basis is called:",a:"divisibility",w:["communicability","compatibility","complexity"],e:"Divisibility in the class notes = trialability in the textbook. Same definition."},
 {tp:"c5",sec:"g5-newprod",t:"mc",q:"In the class notes, the degree to which the results of using an innovation can be observed or described to others is called:",a:"communicability",w:["divisibility","relative advantage","complexity"],e:"Communicability in the class notes = observability in the textbook."},
 {tp:"c5",sec:"g5-newprod",t:"mc",q:"Relative advantage, compatibility, complexity, divisibility and communicability are the five characteristics of:",a:"a product’s rate of adoption",w:["the buyer decision process","the adoption process","brand personality"],e:"The five traits that decide how fast an innovation spreads — divisibility and communicability are the class notes’ names for trialability and observability."},
 {tp:"c5",sec:"g5-newprod",t:"mc",q:"The degree to which an innovation fits the values and experiences of potential consumers is its:",a:"compatibility",w:["complexity","trialability","observability"],e:"Compatibility."},
 {tp:"c5",sec:"g5-newprod",ap:true,t:"mc",q:"A brand that wants people to try its new app offers a free two-week trial. Which adoption characteristic is it improving?",a:"Trialability",w:["Observability","Compatibility","Complexity"],e:"Trying it on a limited basis = trialability."},
 {tp:"c5",sec:"g5-newprod",ap:true,t:"mc",q:"A student sees a friend’s new smartwatch and starts reading about it. Which stage of the adoption process is he in?",a:"Interest",w:["Awareness","Trial","Adoption"],e:"Interest — he is seeking information. Awareness alone would be knowing it exists."},
 {tp:"c5",sec:"g5-newprod",ap:true,t:"mc",q:"A new phone requires learning a completely different operating system. Which characteristic slows its adoption?",a:"Complexity",w:["Relative advantage","Observability","Trialability"],e:"The harder it is to understand or use, the slower the adoption."},
 {tp:"c5",sec:"g5-newprod",ap:true,t:"mc",q:"A fitness tracker’s results are easy to show to friends. Which characteristic speeds its adoption?",a:"Observability",w:["Compatibility","Complexity","Trialability"],e:"Results that can be observed or described to others spread the innovation."},
 {tp:"c5",sec:"g5-newprod",ap:true,t:"mc",q:"An electric car costs far less to run than the gasoline car it replaces. Which characteristic is high?",a:"Relative advantage",w:["Complexity","Trialability","Observability"],e:"The degree to which the innovation appears superior to existing products."},
 {tp:"c5",sec:"g5-newprod",ap:true,t:"mc",q:"A group of buyers waits until most people have tried a product before buying it themselves. They are:",a:"the late mainstream — skeptical",w:["innovators — venturesome","early adopters — guided by respect","the early mainstream — deliberate"],e:"Late mainstream: adopt only after a majority has tried it."},
 {tp:"c5",sec:"g5-newprod",t:"tf",q:"Lagging adopters are the first to try a new product.",a:false,e:"False — they are last; innovators are first."},
 {tp:"c5",sec:"g5-newprod",t:"tf",q:"New-product marketers should direct initial efforts toward innovators and early adopters.",a:true,e:"True — they influence later adopters."},
 {tp:"c5",sec:"g5-newprod",t:"tf",q:"The adoption process ends when the consumer first hears of the product.",a:false,e:"False — it runs from awareness to regular use."}
];
