/* ================================================================ chapter 6
   Business Markets and Business Buyer Behavior. The four sections are the Exam 2
   study guide's. Each explains its point in plain terms first, then the
   concepts; the class's envelope stays only as an illustration.                */
CH.c6 = {n:6, title:"Business Markets and Business Buyer Behavior", short:"Business",
 notes:[
  {id:"c6-intro", h:"Introduction", body:
   '<div class="point"><b>The point</b><p>Business buyers are organizations buying goods and services to make something, to resell it, or to run their operations. Almost every company sells to them — even consumer brands sell first to retailers — and business markets move far more dollars and items than consumer markets do. So B-to-B marketers need to understand business buyers the way consumer marketers understand consumers.</p><p class="able"><b>Be able to</b> define business buyer behavior and the business buying process, and explain why nearly every marketer is at some point a business marketer.</p></div>'+
   '<p><b>Business buyer behavior</b> is the buying behavior of the organizations that buy goods and services for use in the production of other products and services that are sold, rented or supplied to others. It also includes retailers and wholesalers that buy goods to resell or rent at a profit. The <b>business buying process</b> is how business buyers determine which products and services are needed, then find, evaluate and choose among alternative suppliers and brands.</p>'+
   '<p>Most large companies sell mainly to other organizations — Boeing, DuPont, IBM, Caterpillar. Even consumer-products companies first sell to intermediaries: a tire maker sells to car makers for new cars and to retailers for resale. B-to-B marketers must understand business markets and business buyer behavior, then engage business customers and build profitable relationships by creating superior customer value. The business market is huge: it involves far more dollars and items than consumer markets, because each consumer purchase sits on top of a whole chain of business purchases.</p>'},
  {id:"c6-markets", h:"Business Markets", body:
   '<div class="point"><b>The point</b><p>Business markets have fewer, larger, more professional buyers. Their demand is <b>derived</b> from consumer demand, <b>inelastic</b> to price in the short run, and it <b>fluctuates</b> more than consumer demand. Their decisions are more complex and formal, and buyers and sellers depend on each other over the long run.</p><p class="able"><b>Be able to</b> contrast consumer and business markets on structure and demand, the buying unit, and the decision process — and place the pieces of Figure 6.1.</p></div>'+
   '<p class="knowline"><span class="know">Objective 6.1 — how they differ</span></p>'+
   '<p>Both markets involve people in buying roles making decisions to satisfy needs. The differences are in market structure and demand, the nature of the buying unit, and the types of decisions and the decision process.</p>'+
   '<h3 class="sub" id="c6-demand">Market structure and demand</h3>'+
   '<ul><li><b>Fewer but larger buyers</b> — even in large business markets, a few buyers account for most of the purchasing.</li>'+
   '<li><b>Derived demand</b> — business demand ultimately derives from demand for consumer goods. Consumers buy Intel processors only when they buy devices with Intel inside, so Intel’s demand rises and falls with demand for laptops and phones.</li>'+
   '<li><b>Inelastic demand</b> — not much affected by price changes, especially in the short run. A drop in the price of leather will not make shoemakers buy much more leather unless consumers buy more shoes.</li>'+
   '<li><b>Fluctuating demand</b> — changes more, and more quickly, than consumer demand; a small percentage change in consumer demand can cause a large change in business demand, because businesses stop buying equipment and inventory the moment sales slow.</li></ul>'+
   '<h3>Nature of the buying unit</h3>'+
   '<p>A business purchase usually involves <b>more decision participants</b>, <b>more professional purchasing effort</b> (purchasing agents, a formal process, specifications and quotes), <b>more buyer–seller interaction</b> and <b>more time</b>. Large sums, technical and economic considerations, people at many levels, written purchase orders and formal approval. Because business buyers are better trained, B-to-B marketers need well-trained marketers and salespeople to deal with them.</p>'+
   '<h3>Types of decisions and the decision process</h3>'+
   '<p>Business buyers face more complex decisions. In the short run sales go to suppliers who meet immediate needs; in the long run marketers keep customers by partnering to solve their problems. <b>Supplier development</b> is the systematic development of networks of supplier-partners to ensure a dependable supply of products and materials — the buyer builds a network of partners rather than shopping for the cheapest supplier each time.</p>'+
   '<h3 class="sub" id="c6-table">Consumer versus business markets — the comparison from class</h3>'+
   '<div class="tblwrap"><table class="tbl n0"><thead><tr><th>Consumer</th><th>Business</th></tr></thead><tbody>'+
   '<tr><td class="sm">Many, small markets</td><td class="sm">Fewer, large markets</td></tr>'+
   '<tr><td class="sm">Direct demand</td><td class="sm">Derived demand</td></tr>'+
   '<tr><td class="sm">Elastic</td><td class="sm">Inelastic</td></tr>'+
   '<tr><td class="sm">Less fluctuating</td><td class="sm">More fluctuating</td></tr>'+
   '<tr><td class="sm">Consumer = buyer</td><td class="sm">Professional buyer = buyer</td></tr>'+
   '<tr><td class="sm">Simple buying decision</td><td class="sm">Complex buying decision</td></tr>'+
   '<tr><td class="sm">Informal decision process</td><td class="sm">Formal decision process</td></tr>'+
   '<tr><td class="sm">Independent of the seller</td><td class="sm">Buyer and seller are dependent</td></tr>'+
   '</tbody></table></div>'+
   '<h3 class="sub" id="c6-model">Figure 6.1 · The model of business buyer behavior</h3>'+
   '<p>The same shape as the consumer model: stimuli enter the organization, and responses come out. What is different is what happens inside — a buying center rather than one buyer, and a longer, more formal decision process.</p>'+
   '<div class="flow"><div class="step"><b>The environment</b>Marketing stimuli: product, price, place, promotion. Other stimuli: economic, technological, political, cultural, competitive.</div>'+
   '<div class="step"><b>The buying organization</b>The <b>buying center</b> and the <b>buying decision process</b> — with interpersonal and individual influences inside organizational influences.</div>'+
   '<div class="step"><b>Buyer responses</b>Product or service choice, supplier choice, order quantities, delivery terms and times, service terms, payment.</div></div>'},
  {id:"c6-behavior", h:"Business Buyer Behavior", body:
   '<div class="point"><b>The point</b><p>How a business buys depends on the <b>situation</b> — a routine reorder, a change to an old order, or something bought for the first time — and on <b>who takes part</b>: the buying center’s users, influencers, buyers, deciders and gatekeepers, who are in turn shaped by environmental, organizational, interpersonal and individual influences.</p><p class="able"><b>Be able to</b> classify a purchase as straight rebuy, modified rebuy or new task; identify each buying-center role in a story; and sort an influence into one of the four groups of Figure 6.2.</p></div>'+
   '<h3 class="sub" id="c6-situations">Major types of buying situations</h3>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th>Situation</th><th>Definition</th><th>The class’s envelope, as an illustration</th></tr></thead><tbody>'+
   '<tr><td class="head">Straight rebuy</td><td class="sm">The buyer routinely reorders something without any modifications. “In” suppliers try to keep quality up and make reordering automatic; “out” suppliers try to offer something new or exploit dissatisfaction.</td><td class="sm">The same envelope reordered year after year, same size, paper and printing.</td></tr>'+
   '<tr><td class="head">Modified rebuy</td><td class="sm">The buyer wants to modify product specifications, prices, terms or suppliers. “In” suppliers get nervous; “out” suppliers see an opening.</td><td class="sm">The same envelope, but with the opening moved from the side to the top — one line on the quote changes.</td></tr>'+
   '<tr><td class="head">New task</td><td class="sm">The buyer purchases a product or service for the first time. The greater the cost or risk, the more participants and the more information — the marketer’s greatest opportunity and challenge.</td><td class="sm">A clear plastic mailing sleeve instead of an envelope: a new product, new suppliers, a new evaluation.</td></tr>'+
   '</tbody></table></div>'+
   '<p class="ask">Self-test: how would buying a classroom chair differ for the university versus you buying one for your desk? The university buys more, asks the people who will sit in it, organizes the effort, and negotiates bulk pricing — every difference from the section above.</p>'+
   '<h3>Systems selling</h3>'+
   '<p>Many business buyers prefer to buy a <b>complete solution to a problem from a single seller</b> rather than assembling separate products and services from several suppliers. <b>Systems selling</b> (or solutions selling) is often a key strategy for winning and holding accounts: the seller supplies the product <i>and</i> the customizing, installation, training and support that make it work.</p>'+
   '<h3 class="sub" id="c6-center">Participants in the business buying process: the buying center</h3>'+
   '<p class="knowline"><span class="know">The five roles</span></p>'+
   '<p>The <b>buying center</b> is all the individuals and units that play a role in the business purchase decision-making process. It is not a fixed, formally identified unit — it is a set of buying roles assumed by different people for different purchases, and its size and makeup vary by product and situation. One person may play several roles; several people may share one.</p>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th>Role</th><th>Who they are</th><th>For example</th></tr></thead><tbody>'+
   '<tr><td class="head">Users</td><td class="sm">Those who will use the product or service; often initiate the proposal and help define specifications.</td><td class="sm">The operators who will run a new machine; the students and faculty who will sit in new classroom chairs.</td></tr>'+
   '<tr><td class="head">Influencers</td><td class="sm">Help define specifications and provide information for evaluating alternatives; technical personnel are especially important.</td><td class="sm">The engineer who writes the specs; a consultant who recommends a vendor.</td></tr>'+
   '<tr><td class="head">Buyers</td><td class="sm">Have formal authority to select the supplier and arrange terms of purchase.</td><td class="sm">The purchasing agent or purchasing director.</td></tr>'+
   '<tr><td class="head">Deciders</td><td class="sm">Have formal or informal power to select or approve final suppliers; in routine buying, buyers are often the deciders.</td><td class="sm">The CFO or vice president who signs off on a large purchase.</td></tr>'+
   '<tr><td class="head">Gatekeepers</td><td class="sm">Control the flow of information; purchasing agents can keep salespeople from users or deciders — so can technical staff and even receptionists.</td><td class="sm">The receptionist who decides which calls reach the plant manager.</td></tr>'+
   '</tbody></table></div>'+
   '<h3>The marketing challenge</h3>'+
   '<ul><li>Who participates in the decision? What is each participant’s relative influence? What evaluation criteria does each use?</li><li>Are there <b>informal participants</b>? A corporate jet decision can be swayed behind the scenes by a board member who loves flying; sometimes even people in the buying center do not know everyone involved.</li><li>In a typical organization the buying activity has two parts: the buying center and the decision process.</li></ul>'+
   '<h3 class="sub" id="c6-influences">Figure 6.2 · Major influences on business buyers</h3>'+
   '<p class="knowline"><span class="know">Objective 6.2</span></p>'+
   '<p>Business buyers respond to economic factors such as price and quality, but also to personal ones — they are human. Like consumer decisions, business decisions are affected by a complex combination of influences, with an extra layer of <b>organizational</b> factors.</p>'+
   '<div class="boxrow four"><div class="box"><h4>Environmental</h4><ul><li>The economy</li><li>Supply conditions</li><li>Technology</li><li>Politics / regulation</li><li>Competition</li><li>Culture and customs</li></ul></div>'+
   '<div class="box"><h4>Organizational</h4><ul><li>Objectives</li><li>Strategies</li><li>Structure</li><li>Systems</li><li>Procedures</li></ul></div>'+
   '<div class="box"><h4>Interpersonal</h4><ul><li>Influence</li><li>Expertise</li><li>Authority</li><li>Dynamics</li></ul></div>'+
   '<div class="box"><h4>Individual</h4><ul><li>Age / education</li><li>Job position</li><li>Motives</li><li>Personality</li><li>Preferences</li><li>Buying style</li></ul></div></div>'+
   '<ul><li><b>Environmental</b> — the economic outlook, a shortage of key materials (a natural disaster that cuts off a supplier), new technology, regulation, competitors’ moves.</li><li><b>Organizational</b> — the buying company’s own objectives, strategies, structure, systems and procedures: how many people are involved, who they are, what criteria they use, what policies and limits the company places on its buyers.</li><li><b>Interpersonal</b> — who in the buying center has authority, status, expertise or persuasiveness; these are hard to see from outside.</li><li><b>Individual</b> — each participant’s age, education, job position, motives, personality and buying style: some buyers are “keep it simple,” others “tough” or “let’s ask the experts.”</li></ul>'},
  {id:"c6-process", h:"The Business Buyer Decision Process", body:
   '<div class="point"><b>The point</b><p>A business purchase runs through eight steps, from recognizing the problem to reviewing the supplier’s performance afterward — the consumer’s five stages, made longer and more formal. Much of it now happens online through e-procurement, which brings lower costs and faster ordering but can strain supplier relationships.</p><p class="able"><b>Be able to</b> list the eight steps in order, place a scenario in the right step, and give the advantages and the disadvantage of e-procurement.</p></div>'+
   '<h3 class="sub" id="c6-steps">The eight steps</h3>'+
   '<p class="knowline"><span class="know">Objective 6.3</span></p>'+
   '<p>Buyers facing a new task usually go through all eight; modified and straight rebuys skip some.</p>'+
   '<div class="flow">'+
   '<div class="step"><b>1 · Problem recognition</b>Someone recognizes a problem or need — from <b>internal</b> stimuli (a machine breaks down, a manager is unhappy with a supplier) or <b>external</b> stimuli (a trade show, an ad, a better price).</div>'+
   '<div class="step"><b>2 · General need description</b>Describe the characteristics and quantity of the needed item, often with users and engineers.</div>'+
   '<div class="step"><b>3 · Product specification</b>The technical specifications, often with value analysis — can a part be redesigned, standardized or made cheaper?</div>'+
   '<div class="step"><b>4 · Supplier search</b>Find the best vendors — directories, the web, other companies’ recommendations.</div>'+
   '<div class="step"><b>5 · Proposal solicitation</b>Invite qualified suppliers to submit proposals.</div>'+
   '<div class="step"><b>6 · Supplier selection</b>Review proposals and choose one or more suppliers, weighing quality, reputation, delivery, price and service.</div>'+
   '<div class="step"><b>7 · Order-routine specification</b>The final order: specs, quantity, delivery time, return policies, warranties.</div>'+
   '<div class="step"><b>8 · Performance review</b>Rate satisfaction and decide to continue, modify or drop the supplier.</div></div>'+
   '<p>Business marketers often help at step one by alerting customers to problems in their advertising and then showing the solution. Compare the consumer’s five stages (need recognition → information search → evaluation of alternatives → purchase decision → postpurchase behavior): the same shape, with the search and specification work spelled out.</p>'+
   '<h3 class="sub" id="c6-eproc">E-procurement and online purchasing</h3>'+
   '<p><b>E-procurement</b> — purchasing through electronic connections between buyers and sellers, usually online — is standard procedure today. Companies do it through <b>reverse auctions</b> (post purchasing requests and invite suppliers to bid), <b>trading exchanges</b>, their own <b>company buying sites</b>, and <b>extranet</b> links with key suppliers.</p>'+
   '<div class="boxrow"><div class="box"><h4>Advantages</h4><ul><li>Access to new suppliers</li><li>Lowers costs</li><li>Speeds order processing and delivery</li><li>Enhances information sharing</li><li>Improves sales</li><li>Facilitates service and support</li><li>Frees buyers to focus on strategic issues</li></ul></div>'+
   '<div class="box"><h4>Disadvantages</h4><ul><li>Can erode relationships as buyers search for new suppliers</li><li>Buyers use the internet to pit suppliers against one another, purchase by purchase</li></ul></div></div>'+
   '<h3 class="sub" id="c6-instgov">Institutional and government markets</h3>'+
   '<div class="exam-tip"><b>Not on the study guide — but it was in class</b>The handout&rsquo;s four chapter 6 headings leave this out, yet it is in the class notes and in both Quizlet sets. It is short, so learn it rather than gamble.</div>'+
   '<ul><li><b>Institutional markets</b> consist of schools, hospitals, nursing homes and prisons that provide goods and services to the people in their care. They are often characterised by low budgets and captive patrons, and institutions differ in their sponsors and objectives, so each has its own buying needs.</li>'+
   '<li><b>Government markets</b> tend to <b>favour domestic suppliers</b>, <b>require suppliers to submit bids</b>, and normally <b>award the contract to the lowest bidder</b>. They are affected by environmental factors and watched closely by the public, and they weigh <b>non-economic factors</b> too — favouring minority-owned firms, depressed firms and small businesses.</li></ul>'}
 ],
 decks:[
  {id:"terms", label:"Key terms", cards:[
   ["Business buyer behavior","The buying behavior of organizations that buy goods and services to make other products and services sold, rented or supplied to others","g6-intro"],
   ["Business buying process","How business buyers determine what is needed, then find, evaluate and choose among alternative suppliers and brands","g6-intro"],
   ["Derived demand","Business demand that ultimately comes from the demand for consumer goods","g6-markets"],
   ["Inelastic demand","Demand not much affected by price changes, especially in the short run","g6-markets"],
   ["Fluctuating demand","Business demand that changes more, and more quickly, than consumer demand","g6-markets"],
   ["Supplier development","Systematic development of networks of supplier-partners to ensure a dependable supply","g6-markets"],
   ["Straight rebuy","The buyer routinely reorders something without any modifications","g6-behavior"],
   ["Modified rebuy","The buyer wants to modify product specifications, prices, terms or suppliers","g6-behavior"],
   ["New task","The buyer purchases a product or service for the first time","g6-behavior"],
   ["Systems (solutions) selling","Buying a complete solution to a problem from a single seller","g6-behavior"],
   ["Buying center","All the individuals and units that play a role in the business purchase decision process","g6-behavior"],
   ["Users","Members of the organization who will use the product or service","g6-behavior"],
   ["Influencers","People who help define specifications and provide information for evaluating alternatives","g6-behavior"],
   ["Buyers","People with formal authority to select the supplier and arrange terms of purchase","g6-behavior"],
   ["Deciders","People with formal or informal power to select or approve the final suppliers","g6-behavior"],
   ["Gatekeepers","People who control the flow of information to others","g6-behavior"],
   ["Problem recognition","The first stage: someone in the company recognizes a problem or need","g6-process"],
   ["General need description","Describing the characteristics and quantity of a needed item","g6-process"],
   ["Product specification","The technical product specifications, often developed with value analysis","g6-process"],
   ["Supplier search","Finding the best vendors","g6-process"],
   ["Proposal solicitation","Inviting qualified suppliers to submit proposals","g6-process"],
   ["Supplier selection","Reviewing proposals and selecting a supplier or suppliers","g6-process"],
   ["Order-routine specification","The final order — specifications, quantity, delivery time, return policies, warranties","g6-process"],
   ["Performance review","Rating satisfaction with suppliers and deciding to continue, modify or drop them","g6-process"],
   ["E-procurement","Purchasing through electronic connections between buyers and sellers, usually online","g6-process"],
   ["Reverse auction","A buyer posts purchasing requests online and invites suppliers to bid","g6-process"],
   ["Extranet","A direct procurement link with a key supplier","g6-process"]]},
  {id:"lists", label:"Lists & frameworks", cards:[
   ["Who business buyers are","Organizations buying to produce, to resell or rent, or to run their operations","g6-intro"],
   ["Why the business market is bigger than the consumer market","Every consumer purchase sits on a chain of business purchases — far more dollars and items","g6-intro"],
   ["Four differences in business demand","Fewer but larger buyers; derived; inelastic; fluctuating","g6-markets"],
   ["What a business purchase involves more of","More decision participants, more professional purchasing effort, more buyer–seller interaction, more time","g6-markets"],
   ["Figure 6.1 buyer responses","Product or service choice, supplier choice, order quantities, delivery terms and times, service terms, payment","g6-markets"],
   ["The three buying situations","Straight rebuy, modified rebuy, new task","g6-behavior"],
   ["Which buying situation is the marketer’s greatest opportunity and challenge","New task — the most participants and the most information","g6-behavior"],
   ["The five buying-center roles","Users, influencers, buyers, deciders, gatekeepers","g6-behavior"],
   ["The four groups of influences (Figure 6.2)","Environmental, organizational, interpersonal, individual","g6-behavior"],
   ["Environmental influences","The economy, supply conditions, technology, politics and regulation, competition, culture and customs","g6-behavior"],
   ["Organizational influences","Objectives, strategies, structure, systems, procedures","g6-behavior"],
   ["Interpersonal influences","Influence, expertise, authority, dynamics","g6-behavior"],
   ["Individual influences","Age and education, job position, motives, personality, preferences, buying style","g6-behavior"],
   ["The eight steps","Problem recognition, general need description, product specification, supplier search, proposal solicitation, supplier selection, order-routine specification, performance review","g6-process"],
   ["Internal vs external stimuli for problem recognition","Internal: a breakdown, an unhappy manager. External: a trade show, an ad, a better price","g6-process"],
   ["Four ways to do e-procurement","Reverse auctions, trading exchanges, company buying sites, extranet links","g6-process"],
   ["The main disadvantage of e-procurement","It can erode relationships as buyers search for new suppliers","g6-process"],
   ["Institutional markets","Schools, hospitals, nursing homes and prisons that provide goods and services to the people in their care","g6-process"],
   ["Government markets","Favour domestic suppliers, require bids, normally award to the lowest bidder — and weigh non-economic factors","g6-process"]]}
 ]
};

QB = QB.concat([
 {tp:"c6",sec:"g6-intro",t:"mc",q:"Business buyer behavior refers to the buying behavior of organizations that buy goods and services:",a:"for use in producing other products and services that are sold, rented or supplied to others",w:["for personal consumption","only for resale to consumers","only from the government"],e:"To make other products and services — or to resell."},
 {tp:"c6",sec:"g6-intro",t:"mc",q:"The business buying process is:",a:"how business buyers determine which products and services are needed, then find, evaluate and choose among suppliers and brands",w:["the five stages a consumer goes through","the process of setting prices for business customers","the way retailers display products"],e:"Determine the need, then find, evaluate and choose."},
 {tp:"c6",sec:"g6-intro",t:"mc",q:"Why are even consumer-products companies business marketers?",a:"Because they first sell to intermediaries such as retailers, which are business buyers",w:["Because consumers buy in bulk","Because the government regulates them","Because they never sell to individuals"],e:"A consumer brand’s first customer is usually a retailer or wholesaler."},
 {tp:"c6",sec:"g6-intro",ap:true,t:"mc",q:"A tire maker sells tires to a car manufacturer for new cars and to auto-parts stores for resale. Both of these customers are:",a:"business buyers",w:["final consumers","unsought markets","consumer markets"],e:"One buys to produce, the other to resell — both are business markets."},
 {tp:"c6",sec:"g6-intro",t:"mc",q:"Which of these is NOT a business buyer?",a:"A family buying a car for weekend trips",w:["A factory buying steel to make appliances","A supermarket buying cereal to resell","A hospital buying cleaning supplies for its operations"],e:"Buying to produce, to resell, or to run operations is business buying; the family buys for personal consumption."},
 {tp:"c6",sec:"g6-intro",t:"mc",q:"Why does the business market involve more dollars and items than the consumer market?",a:"Each consumer purchase sits on top of a whole chain of business purchases — materials, parts, equipment, services",w:["Businesses pay higher prices for the same goods","Consumers buy only once a year","Business buyers are counted twice"],e:"Everything a consumer buys was first bought and sold many times between businesses."},
 {tp:"c6",sec:"g6-intro",t:"tf",q:"Business markets involve far more dollars and items than consumer markets.",a:true,e:"True — every consumer purchase rests on a chain of business purchases."},
 {tp:"c6",sec:"g6-intro",t:"tf",q:"Retailers and wholesalers that buy goods to resell are part of the business market.",a:true,e:"True — buying to resell or rent at a profit is business buying."},

 {tp:"c6",sec:"g6-markets",t:"mc",q:"Compared with consumer markets, business markets have:",a:"fewer but larger buyers",w:["more but smaller buyers","the same number of buyers","buyers who are less professional"],e:"Fewer but larger; a few buyers often account for most purchasing."},
 {tp:"c6",sec:"g6-markets",t:"mc",q:"Consumers buy Intel processors only when they buy devices with Intel inside. This illustrates:",a:"derived demand",w:["inelastic demand","fluctuating demand","elastic demand"],e:"Business demand is derived from consumer demand."},
 {tp:"c6",sec:"g6-markets",t:"mc",q:"Demand for many business products is not affected much by price changes in the short run. This is:",a:"inelastic demand",w:["derived demand","fluctuating demand","direct demand"],e:"Inelastic — a cheaper input does not by itself sell more of the final product."},
 {tp:"c6",sec:"g6-markets",t:"mc",q:"A small percentage change in consumer demand can cause a large change in business demand. This is:",a:"fluctuating demand",w:["inelastic demand","derived demand","habitual demand"],e:"Fluctuating — businesses cut equipment and inventory purchases sharply as soon as sales slow."},
 {tp:"c6",sec:"g6-markets",t:"mc",q:"Why is business demand inelastic in the short run?",a:"A change in the price of an input does not change how much of the final product consumers buy",w:["Business buyers do not care about price","Suppliers fix prices by contract","Business buyers always buy the same quantity"],e:"Cheaper leather does not make shoemakers buy much more leather unless people buy more shoes."},
 {tp:"c6",sec:"g6-markets",t:"mc",q:"Which of these describes a business purchase rather than a consumer purchase?",a:"Formal decision process",w:["Direct demand","Elastic demand","Independent of the seller"],e:"Business: derived, inelastic, more fluctuating, professional buyer, complex and formal, buyer and seller dependent."},
 {tp:"c6",sec:"g6-markets",t:"mc",q:"Compared with a consumer purchase, a business purchase usually involves:",a:"more decision participants, more professional effort, more buyer–seller interaction and more time",w:["fewer people and a faster decision","less money and less risk","no written orders or formal approval"],e:"The nature of the buying unit."},
 {tp:"c6",sec:"g6-markets",t:"mc",q:"Supplier development is:",a:"the systematic development of networks of supplier-partners to ensure a dependable supply",w:["training a supplier’s sales force","buying from whichever supplier is cheapest today","a reverse auction among suppliers"],e:"A network of partners, not spot purchases."},
 {tp:"c6",sec:"g6-markets",t:"mc",q:"In Figure 6.1, which of these is one of the buyer responses?",a:"Supplier choice",w:["Cultural stimuli","The buying center","Competitive stimuli"],e:"Responses: product or service choice, supplier choice, order quantities, delivery terms and times, service terms, payment."},
 {tp:"c6",sec:"g6-markets",t:"mc",q:"What sits inside the buying organization in Figure 6.1, where the consumer model has the black box?",a:"The buying center and the buying decision process",w:["The four Ps","The buyer responses","The economic and technological stimuli"],e:"A buying center rather than one buyer, and a longer, more formal process."},
 {tp:"c6",sec:"g6-markets",ap:true,t:"mc",q:"Home sales fall 5%, and orders for lumber-mill equipment fall 40%. This illustrates:",a:"fluctuating (derived) demand",w:["inelastic demand","elastic consumer demand","a straight rebuy"],e:"A small change in consumer demand → a large change in business demand."},
 {tp:"c6",sec:"g6-markets",ap:true,t:"mc",q:"A restaurant chain builds long-term partnerships with a few trusted produce suppliers instead of taking bids every week. This is:",a:"supplier development",w:["a reverse auction","e-procurement","a new task"],e:"A dependable network of supplier-partners."},
 {tp:"c6",sec:"g6-markets",t:"tf",q:"Business demand is described as inelastic because it is not much affected by price changes in the short run.",a:true,e:"True."},
 {tp:"c6",sec:"g6-markets",t:"tf",q:"Business buyers and sellers tend to be more dependent on each other than consumers and sellers are.",a:true,e:"True — the last row of the comparison table."},
 {tp:"c6",sec:"g6-markets",t:"tf",q:"Business demand is more stable than consumer demand.",a:false,e:"False — it fluctuates more, and faster."},

 {tp:"c6",sec:"g6-behavior",t:"mc",q:"The buyer routinely reorders something without any modifications. This is a:",a:"straight rebuy",w:["modified rebuy","new task","systems purchase"],e:"Straight rebuy — the same envelope, year after year."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Which buying situation is the marketer’s greatest opportunity and challenge?",a:"New task",w:["Straight rebuy","Modified rebuy","Systems selling"],e:"The most participants and the most information — and no incumbent supplier."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"In a straight rebuy, an “out” supplier tries to:",a:"offer something new or exploit dissatisfaction so the buyer will consider it",w:["make reordering automatic","keep quality exactly the same","avoid contact with the buyer"],e:"The “in” supplier automates reordering; the “out” supplier needs a reason for the buyer to look again."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Buying a complete solution to a problem from a single seller is called:",a:"systems selling",w:["straight rebuy","supplier development","e-procurement"],e:"Systems (solutions) selling."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"All the individuals and units that play a role in the business purchase decision process make up the:",a:"buying center",w:["purchasing department","supplier network","procurement committee"],e:"The buying center — a set of roles, not a fixed unit."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Which is true of the buying center?",a:"Its size and makeup vary by product and buying situation",w:["It is a fixed department listed on the organization chart","It always has exactly five people","Only the purchasing agent belongs to it"],e:"A set of buying roles assumed by different people for different purchases."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Which buying-center role has formal authority to select the supplier and arrange terms?",a:"Buyers",w:["Users","Influencers","Gatekeepers"],e:"Buyers."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Which buying-center role controls the flow of information?",a:"Gatekeepers",w:["Deciders","Users","Buyers"],e:"Gatekeepers — purchasing agents, technical staff, even receptionists."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Which buying-center role has formal or informal power to select or approve the final suppliers?",a:"Deciders",w:["Influencers","Gatekeepers","Users"],e:"Deciders — in routine buying, the buyers are often the deciders."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Technical personnel are especially important in which buying-center role?",a:"Influencers",w:["Gatekeepers","Deciders","Users"],e:"They help define specifications and evaluate alternatives."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Which is an ORGANIZATIONAL influence on business buyers?",a:"Procedures",w:["Supply conditions","Expertise","Buying style"],e:"Organizational: objectives, strategies, structure, systems, procedures."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Which is an INTERPERSONAL influence on business buyers?",a:"Authority",w:["Technology","Job position","Competition"],e:"Interpersonal: influence, expertise, authority, dynamics."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Which is an INDIVIDUAL influence on business buyers?",a:"Buying style",w:["Regulation","Company structure","Supply conditions"],e:"Individual: age and education, job position, motives, personality, preferences, buying style."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Objectives, strategies, structure, systems and procedures are the:",a:"organizational factors",w:["environmental factors","interpersonal factors","individual factors"],e:"The organizational layer of Figure 6.2 — the buying company’s own policies and limits."},
 {tp:"c6",sec:"g6-behavior",t:"mc",q:"Business buyers are influenced by:",a:"economic factors such as price and quality and also personal factors — they are human",w:["economic factors only","personal factors only","the government’s purchasing rules"],e:"They respond to both reason and emotion."},
 {tp:"c6",sec:"g6-behavior",ap:true,t:"mc",q:"An engineer writes the technical specs that a new part must meet. Which buying-center role is she playing?",a:"Influencer",w:["Gatekeeper","Buyer","User"],e:"Influencers help define specifications; technical personnel are especially important."},
 {tp:"c6",sec:"g6-behavior",ap:true,t:"mc",q:"A receptionist declines to put a salesperson through to the plant manager. Which role is that?",a:"Gatekeeper",w:["Decider","Buyer","Influencer"],e:"Controlling the flow of information = gatekeeper."},
 {tp:"c6",sec:"g6-behavior",ap:true,t:"mc",q:"The machine operators complain about the old equipment and ask for a replacement. Which role are they playing?",a:"Users",w:["Deciders","Buyers","Gatekeepers"],e:"Users often initiate the proposal and help define what is needed."},
 {tp:"c6",sec:"g6-behavior",ap:true,t:"mc",q:"The CFO must approve any purchase over $100,000 before the purchasing agent can place the order. The CFO is a:",a:"decider",w:["user","gatekeeper","influencer"],e:"Formal power to approve the final supplier."},
 {tp:"c6",sec:"g6-behavior",ap:true,t:"mc",q:"A university orders the same envelopes it has ordered for years, with no changes. This is:",a:"a straight rebuy",w:["a modified rebuy","a new task","systems selling"],e:"Routine reorder, no modifications."},
 {tp:"c6",sec:"g6-behavior",ap:true,t:"mc",q:"A company that has bought the same envelope for years asks its supplier to move the opening from the side to the top. This is:",a:"a modified rebuy",w:["a straight rebuy","a new task","a reverse auction"],e:"A modified specification = modified rebuy."},
 {tp:"c6",sec:"g6-behavior",ap:true,t:"mc",q:"A company that has always used paper envelopes orders clear plastic mailing sleeves for the first time. This is:",a:"a new task",w:["a modified rebuy","a straight rebuy","a performance review"],e:"A product bought for the first time = new task."},
 {tp:"c6",sec:"g6-behavior",ap:true,t:"mc",q:"A software vendor sells not just the program but installation, customization and training as one package. This is:",a:"systems selling",w:["a reverse auction","supplier development","a straight rebuy"],e:"A complete solution from a single seller."},
 {tp:"c6",sec:"g6-behavior",ap:true,t:"mc",q:"A flood shuts down a key supplier’s factory and a company must find new sources of a part. Which group of influences is at work?",a:"Environmental — supply conditions",w:["Organizational — procedures","Interpersonal — authority","Individual — buying style"],e:"Supply conditions are an environmental influence."},
 {tp:"c6",sec:"g6-behavior",ap:true,t:"mc",q:"A company’s policy requires three written bids for every purchase over $10,000. Which group of influences is that?",a:"Organizational",w:["Environmental","Interpersonal","Individual"],e:"The buying company’s own procedures and limits on its buyers."},
 {tp:"c6",sec:"g6-behavior",ap:true,t:"mc",q:"In a buying center, everyone defers to the one engineer who really understands the equipment. Which group of influences is that?",a:"Interpersonal — expertise",w:["Environmental — technology","Organizational — structure","Individual — motives"],e:"Who has authority, status or expertise inside the buying center."},
 {tp:"c6",sec:"g6-behavior",t:"tf",q:"The buying center is a fixed, formally identified unit within the organization.",a:false,e:"False — it is a set of roles assumed by different people for different purchases."},
 {tp:"c6",sec:"g6-behavior",t:"tf",q:"In routine buying, the buyers are often the deciders.",a:true,e:"True."},
 {tp:"c6",sec:"g6-behavior",t:"tf",q:"Sometimes even people in the buying center are not aware of all the buying participants.",a:true,e:"True — informal participants may sway the decision behind the scenes."},
 {tp:"c6",sec:"g6-behavior",t:"tf",q:"Business buying decisions have the same four groups of influences as consumer decisions, with an extra organizational layer.",a:true,e:"True — environmental, interpersonal, individual, plus organizational."},
 {tp:"c6",sec:"g6-behavior",t:"tf",q:"A new-task purchase usually involves fewer decision participants than a straight rebuy.",a:false,e:"False — the more new and risky the purchase, the more participants and information."},

 {tp:"c6",sec:"g6-process",t:"mc",q:"The first step of the business buying process is:",a:"problem recognition",w:["supplier search","general need description","proposal solicitation"],e:"Problem recognition, from internal or external stimuli."},
 {tp:"c6",sec:"g6-process",t:"mc",q:"The last step of the business buying process is:",a:"performance review",w:["order-routine specification","supplier selection","postpurchase behavior"],e:"Performance review — continue, modify or drop the supplier."},
 {tp:"c6",sec:"g6-process",t:"mc",q:"Which step comes immediately after supplier search?",a:"Proposal solicitation",w:["Supplier selection","Product specification","Order-routine specification"],e:"…product specification → supplier search → proposal solicitation → supplier selection…"},
 {tp:"c6",sec:"g6-process",t:"mc",q:"How many steps are in the business buying process?",a:"Eight",w:["Five","Four","Ten"],e:"Eight — versus five stages for consumers."},
 {tp:"c6",sec:"g6-process",t:"mc",q:"Which buyers usually go through all eight steps?",a:"Buyers facing a new task",w:["Buyers making a straight rebuy","Buyers making a modified rebuy","All buyers, every time"],e:"Modified and straight rebuys skip some of the steps."},
 {tp:"c6",sec:"g6-process",t:"mc",q:"A machine breaks down and needs new parts. In the business buying process this is:",a:"an internal stimulus for problem recognition",w:["an external stimulus for problem recognition","proposal solicitation","order-routine specification"],e:"Internal stimulus. A trade show or an ad would be external."},
 {tp:"c6",sec:"g6-process",t:"mc",q:"Value analysis — asking whether a part can be redesigned, standardized or made more cheaply — belongs to which step?",a:"Product specification",w:["General need description","Supplier search","Performance review"],e:"Step 3, the technical specifications."},
 {tp:"c6",sec:"g6-process",t:"mc",q:"Putting purchasing requests online and inviting suppliers to bid for the business is a:",a:"reverse auction",w:["trading exchange","extranet","straight rebuy"],e:"A reverse auction."},
 {tp:"c6",sec:"g6-process",t:"mc",q:"A disadvantage of e-procurement is that it:",a:"can erode buyer–supplier relationships",w:["raises purchasing costs","slows order processing","limits access to new suppliers"],e:"Buyers use the web to pit suppliers against each other purchase by purchase."},
 {tp:"c6",sec:"g6-process",ap:true,t:"mc",q:"A company puts its need for 10,000 laptops online and lets suppliers bid the price down. This is:",a:"a reverse auction",w:["an extranet","systems selling","a modified rebuy"],e:"Reverse auction."},
 {tp:"c6",sec:"g6-process",ap:true,t:"mc",q:"A purchasing agent meets with users and engineers to write down what the new item must do and how many are needed. Which step is this?",a:"General need description",w:["Problem recognition","Supplier selection","Order-routine specification"],e:"Step 2 — the characteristics and quantity of the needed item."},
 {tp:"c6",sec:"g6-process",ap:true,t:"mc",q:"A company invites four qualified vendors to submit written proposals. Which step is this?",a:"Proposal solicitation",w:["Supplier search","Supplier selection","Product specification"],e:"Step 5."},
 {tp:"c6",sec:"g6-process",ap:true,t:"mc",q:"Each quarter a company rates its supplier’s delivery, quality and service and decides whether to keep it. Which step is this?",a:"Performance review",w:["Order-routine specification","Supplier selection","General need description"],e:"Step 8 — continue, modify or drop."},
 {tp:"c6",sec:"g6-process",ap:true,t:"mc",q:"The final order lists the quantity, delivery dates, return policy and warranty. Which step is this?",a:"Order-routine specification",w:["Proposal solicitation","Supplier search","Problem recognition"],e:"Step 7."},
 {tp:"c6",sec:"g6-process",ap:true,t:"mc",q:"A manufacturer links its purchasing system directly to a key supplier so parts are reordered automatically. This is:",a:"an extranet link",w:["a reverse auction","a trading exchange","systems selling"],e:"A direct procurement link with a key supplier."},
 {tp:"c6",sec:"g6-process",t:"tf",q:"E-procurement gives buyers access to new suppliers and lowers purchasing costs.",a:true,e:"True — and it speeds order processing and delivery."},
 {tp:"c6",sec:"g6-process",t:"tf",q:"E-procurement frees buyers’ time to focus on strategic issues.",a:true,e:"True."},
 {tp:"c6",sec:"g6-process",t:"tf",q:"The consumer decision process has more steps than the business buying process.",a:false,e:"False — five vs eight."},
 {tp:"c6",sec:"g6-process",t:"tf",q:"Business marketers can help start the buying process by alerting customers to problems and showing the solution.",a:true,e:"True — problem recognition can come from an external stimulus such as an ad."},
 {tp:"c6",sec:"g6-process",t:"mc",q:"Institutional markets consist of:",a:"schools, hospitals, nursing homes and prisons that provide goods and services to the people in their care",w:["federal, state and local government agencies","retailers and wholesalers that resell goods","factories that buy parts for production"],e:"Often low budgets and captive patrons. In the class notes, not on the study guide."},
 {tp:"c6",sec:"g6-process",t:"mc",q:"Government markets normally award the contract to:",a:"the lowest bidder",w:["the supplier with the best reputation","the fastest supplier","whichever supplier bids first"],e:"They favour domestic suppliers, require bids, and normally take the lowest bidder."},
 {tp:"c6",sec:"g6-process",t:"mc",q:"Besides price, which non-economic factors do government buyers weigh?",a:"Favouring minority-owned firms, depressed firms and small businesses",w:["The supplier’s advertising budget","The buyer’s personal preferences","The supplier’s stock price"],e:"Government buying is watched by the public and carries social goals."},
 {tp:"c6",sec:"g6-process",t:"tf",q:"Government buyers usually require suppliers to submit bids and favour domestic suppliers.",a:true,e:"True — bids, domestic preference, and normally the lowest bidder."},
 {tp:"c6",sec:"g6-process",ap:true,t:"mc",q:"A state prison system buys food and bedding for the people in its care. Which market is that?",a:"The institutional market",w:["The government market","The consumer market","The reseller market"],e:"Schools, hospitals, nursing homes and prisons that serve people in their care."}
]);
