/* ================================================================ chapter 7
   Customer Value–Driven Marketing Strategy. The four sections are the Exam 2
   study guide's. Each explains its point in plain terms first, then the
   concepts; company examples stay only where they show a concept at work.     */
CH.c7 = {n:7, title:"Customer Value–Driven Marketing Strategy", short:"Strategy",
 notes:[
  {id:"c7-strategy", h:"Marketing Strategy", body:
   '<div class="point"><b>The point</b><p>A customer-driven strategy answers two questions. <b>Which customers will we serve?</b> — segmentation and targeting. <b>How will we serve them?</b> — differentiation and positioning, which together form the value proposition. Everything sits around one goal: creating value for the customers the company chooses.</p><p class="able"><b>Be able to</b> name the four steps of Figure 7.1, say which question each pair answers, and define target marketing.</p></div>'+
   '<p class="knowline"><span class="know">Objective 7.1 — the four steps</span></p>'+
   '<p>Companies cannot appeal to all buyers in the marketplace, or at least not to all in the same way — buyers are too numerous, too scattered and too varied. Most have moved from mass marketing to <b>target marketing</b>: identifying market segments, selecting one or more, and developing products and programs tailored to each.</p>'+
   '<div class="quote">Marketing boils down to two questions: 1. Which customers will we serve? 2. How will we serve them? The goal is to create more value for the customers we serve than competitors do.<small>Figure 7.1 note</small></div>'+
   '<h3>Figure 7.1 · Designing a customer-driven marketing strategy</h3>'+
   '<div class="boxrow"><div class="box"><h4>Select customers to serve</h4><ul><li><b>Segmentation</b> — divide the total market into smaller segments.</li><li><b>Targeting</b> — select the segment or segments to enter.</li></ul></div>'+
   '<div class="box"><h4>Decide on a value proposition</h4><ul><li><b>Differentiation</b> — differentiate the market offering to create superior customer value.</li><li><b>Positioning</b> — position the market offering in the minds of target customers.</li></ul></div></div>'+
   '<p>At the center of the figure: <b>create value for targeted customers</b>. The four steps go in order — a company has to know whom it is serving before it can decide how to stand out for them.</p>'},
  {id:"c7-seg", h:"Market Segmentation", body:
   '<div class="point"><b>The point</b><p>Segmentation divides a market into groups that want different things. Consumer markets are divided by <b>geography</b>, <b>demographics</b>, <b>psychographics</b> and <b>behavior</b> (occasions, benefits, user status, usage rate, loyalty), usually with several bases combined. A segment is only worth using if it is <b>measurable, accessible, substantial, differentiable and actionable</b>.</p><p class="able"><b>Be able to</b> identify the base a company is using from an example, and name which requirement a proposed segment fails.</p></div>'+
   '<h3 class="sub" id="c7-bases">Segmenting consumer markets</h3>'+
   '<p class="knowline"><span class="know">Objective 7.2 — the bases</span></p>'+
   '<p><b>Market segmentation</b> divides a market into smaller segments with distinct needs, characteristics or behaviors that might require separate marketing strategies or mixes. Buyers differ in wants, resources, locations, buying attitudes and buying practices; segmentation lets companies reach smaller groups more efficiently and effectively with products and services that match their needs.</p>'+
   '<h3>Geographic</h3><p>Nations, regions, states, counties, cities, even neighborhoods. A company can operate in a few areas, or in all of them while paying attention to local differences — a pizza chain that runs local coupons and store-by-store promotions.</p>'+
   '<h3>Demographic</h3><p>Age, life-cycle stage, gender, income, occupation, education, religion, ethnicity, generation. The <b>most popular</b> bases, because needs and usage vary closely with them and they are <b>easier to measure</b> than most other variables — even segments defined by benefits or behavior need demographics to size and reach the target.</p>'+
   '<ul><li><b>Age and life-cycle stage</b> — needs and wants change with age (a streaming service with a children’s tier), but guard against stereotypes: two people the same age can be at very different stages of life.</li><li><b>Gender</b> — long used for clothing, cosmetics and personal care; now brands cross over, with men’s lines from cosmetics makers and women’s lines from tool makers.</li><li><b>Income</b> — automobiles, clothing, cosmetics, financial services, travel. Not only the affluent: dollar stores target families with modest incomes and do very well.</li></ul>'+
   '<h3>Psychographic</h3><p>Social class, lifestyle, personality. People in the same demographic group can have very different psychographic characteristics — two coffee chains can sell to the same age and income bracket, one to the “average Joe,” the other to the coffee connoisseur. Brands take on personalities to match: youthful and rebellious, or mature and practical.</p>'+
   '<h3>Behavioral</h3><p>Consumer knowledge, attitudes, uses of a product, responses to a product. Many marketers believe behavior variables are the <b>best starting point</b> for building segments, because they describe what people actually do with the product.</p>'+
   '<div class="tblwrap"><table class="tbl n0"><tbody>'+
   '<tr><td class="head">Occasions</td><td class="sm">When consumers get the idea to buy, actually buy, or use the item. Soup is advertised more heavily in winter; lawn-and-garden promotions run in spring.</td></tr>'+
   '<tr><td class="head">Benefits sought</td><td class="sm">Why — what need is addressed. Find the major benefits people look for, the kinds of people who look for each, and the brands that deliver each. A bike maker builds a different bike for every reason people ride: commuting, fitness, trails, cruising.</td></tr>'+
   '<tr><td class="head">User status</td><td class="sm">Who: nonusers, ex-users, potential users, first-time users, regular users. Retain regulars, attract nonusers, reinvigorate ex-users.</td></tr>'+
   '<tr><td class="head">Usage rate</td><td class="sm">How much: light, medium, heavy. Heavy users are a small share of the market but a large share of consumption, so marketers often prefer to win one heavy user over several light ones.</td></tr>'+
   '<tr><td class="head">Loyalty status</td><td class="sm">How attached: completely loyal (buy the brand every time and join its loyalty program), somewhat loyal (two or three brands), not loyal at all (want something different each time, or buy what’s on sale).</td></tr>'+
   '</tbody></table></div>'+
   '<h3>Multiple segmentation bases</h3><p>Marketers rarely stop at one variable. Commercial systems combine demographics, lifestyle and behavior into segments with names like “Skyboxes and Suburbans” and “Soccer and SUVs.” Why: to identify and understand key segments, reach them efficiently, and tailor offerings and messages to their specific needs.</p>'+
   '<h3 class="sub" id="c7-req">Requirements for effective segmentation</h3>'+
   '<p class="knowline"><span class="know">Five requirements</span></p>'+
   '<p>There are many ways to segment a market, but not all of them are useful. To be worth using, a segment must be:</p>'+
   '<div class="levels">'+
   '<div class="lv"><b>Measurable</b><span>The size, purchasing power and profiles of the segment can be measured.</span></div>'+
   '<div class="lv"><b>Accessible</b><span>The segments can be effectively reached and served.</span></div>'+
   '<div class="lv"><b>Substantial</b><span>The segments are large or profitable enough to serve.</span></div>'+
   '<div class="lv"><b>Differentiable</b><span>The segments are conceptually distinguishable and respond differently to marketing mix elements — if two segments respond the same way, they are one segment.</span></div>'+
   '<div class="lv"><b>Actionable</b><span>Effective programs can be designed and executed for attracting and serving the segments.</span></div></div>'},
  {id:"c7-target", h:"Market Targeting", body:
   '<div class="point"><b>The point</b><p>Targeting first evaluates segments — size and growth, structural attractiveness, and fit with the company’s objectives and resources — then chooses how many to serve: everyone with one offer, several segments with separate offers, one niche, or individual customers and localities. Resources, product and market variability, life-cycle stage and competitors’ strategies decide which.</p><p class="able"><b>Be able to</b> judge a segment’s attractiveness, name the targeting strategy in a scenario, and say which factor points to which strategy.</p></div>'+
   '<h3 class="sub" id="c7-eval">Evaluating market segments</h3>'+
   '<p class="knowline"><span class="know">Objective 7.3</span></p>'+
   '<p><b>Market targeting</b> involves evaluating each segment’s attractiveness and selecting one or more segments to enter. A <b>target market</b> is a set of buyers who share common needs or characteristics that the company decides to serve.</p>'+
   '<ul><li><b>Segment size and growth</b> — relative; the largest, fastest-growing segments are not always the most attractive for every company. Smaller companies may lack the resources to compete there and do better in smaller segments that are more profitable for them.</li><li><b>Segment structural attractiveness</b> — a segment is less attractive when it has strong and aggressive competitors, easy entry for new competitors, substitute products that cap prices, powerful buyers who can force prices down, or powerful suppliers who control prices or quality.</li><li><b>Company objectives and resources</b> — enter only segments where the company can create superior value and gain an advantage; an attractive segment that does not fit the company’s long-run objectives should be dismissed.</li></ul>'+
   '<h3 class="sub" id="c7-strategies">Figure 7.2 · Market-targeting strategies, broad to narrow</h3>'+
   '<div class="flow">'+
   '<div class="step"><b>Undifferentiated (mass)</b>One offer to the whole market, focused on common needs rather than differences. Most modern marketers doubt it: hard to satisfy everyone, and focused firms do better in specific segments.</div>'+
   '<div class="step"><b>Differentiated (segmented)</b>Several segments, a separate offer for each. Higher sales and a stronger position, but more expensive to execute — weigh the extra sales against the extra costs. A hotel company runs many brands, each for a different traveler: luxury, upscale, business, extended stay, budget.</div>'+
   '<div class="step"><b>Concentrated (niche)</b>A large share of one or a few smaller segments. Fits limited resources and deep knowledge of the market; more effective and efficient — a razor start-up selling direct to a value-and-convenience segment the giants underserved. Higher risk: if the segment sours or a giant enters, the company suffers.</div>'+
   '<div class="step"><b>Micromarketing</b>Tailoring to specific individuals and locations. <b>Local marketing</b> — cities, neighborhoods, stores (a department store tailoring assortments district by district; location-based mobile offers); drawbacks: higher costs, logistics, a diluted image. <b>Individual marketing</b> — one-to-one, mass customization: a car maker designing a car with each customer; candies printed with your children’s faces.</div></div>'+
   '<div class="quote">Rather than seeing a customer in every individual, micromarketers see the individual in every customer.<small>Kotler</small></div>'+
   '<h3 class="sub" id="c7-choose">Choosing a targeting strategy</h3>'+
   '<ul><li><b>Company resources</b> — limited resources → concentrated.</li><li><b>Product variability</b> — uniform products (grapefruit, steel) → undifferentiated; products that can vary in design (cars, cameras) → differentiated or concentrated.</li><li><b>Product life-cycle stage</b> — a new product may launch one version; in maturity, differentiated makes more sense.</li><li><b>Market variability</b> — if buyers have the same tastes, buy the same amounts and react the same way → undifferentiated.</li><li><b>Competitors’ strategies</b> — when competitors go undifferentiated, gain an edge with differentiated or concentrated marketing; when they segment, undifferentiated marketing can be suicidal.</li></ul>'},
  {id:"c7-position", h:"Differentiation and Positioning", body:
   '<div class="point"><b>The point</b><p>A <b>position</b> is the place a brand holds in customers’ minds relative to competitors. Companies earn it by <b>differentiating</b> — on product, services, channels, people or image — choosing the differences worth promoting, picking a <b>value proposition</b> (more for more … less for much less), stating the position in one sentence, and then delivering it consistently.</p><p class="able"><b>Be able to</b> identify the type of differentiation, classify a value proposition, test a difference against the seven criteria, and write a positioning statement.</p></div>'+
   '<h3 class="sub" id="c7-diff">Differentiation and positioning</h3>'+
   '<p class="knowline"><span class="know">Objective 7.4</span></p>'+
   '<p><b>Product position</b> is the way the product is defined by consumers on important attributes — the place it occupies in consumers’ minds relative to competing products. <b>Products are made in factories, but brands happen in the minds of consumers.</b> One furniture store is “the life improvement store”; one detergent is the gentle one for baby clothes; some cars are positioned on economy, others on luxury, others on performance. Consumers position products with or without marketers — so marketers plan positions rather than leave them to chance.</p>'+
   '<p><b>Differentiation</b> means making the market offering different to create superior customer value. <b>Competitive advantage</b> is an advantage over competitors gained by offering greater value — through lower prices, or more benefits that justify higher prices. Solid positions cannot be built on empty promises: a company must first <i>live</i> the slogan.</p>'+
   '<h3>Choosing a strategy — four steps</h3>'+
   '<ol><li>Identify a set of possible competitive advantages to build a position on.</li><li>Choose the right competitive advantages.</li><li>Select an overall positioning strategy.</li><li>Communicate and deliver the chosen position to the market.</li></ol>'+
   '<h3>Where to differentiate</h3>'+
   '<div class="tblwrap"><table class="tbl n0"><tbody>'+
   '<tr><td class="head">Product</td><td class="sm">Features, performance, style and design — “better sound through research”; the healthy fast-food choice.</td></tr>'+
   '<tr><td class="head">Services</td><td class="sm">Speedy, convenient or careful delivery; installation, repair, training — a sandwich chain built on “freaky fast” delivery.</td></tr>'+
   '<tr><td class="head">Channels</td><td class="sm">Coverage, expertise and performance of the channel — a retailer or insurer that wins through smooth direct channels.</td></tr>'+
   '<tr><td class="head">People</td><td class="sm">Hiring and training better people than competitors — a hotel or airline known for its staff.</td></tr>'+
   '<tr><td class="head">Image</td><td class="sm">Symbols, characters and image elements communicated through advertising that conveys the brand’s personality.</td></tr>'+
   '</tbody></table></div>'+
   '<p>Two coffee-and-snack chains can both succeed side by side: one targets the average Joe on the go, the other the upscale customer who wants a destination. Each creates the right value proposition for its own mix of customers — which is the point of positioning.</p>'+
   '<h3>Which differences are worth establishing</h3>'+
   '<p>Not all brand differences are meaningful; each can create costs as well as benefits. A difference is worth it to the extent that it is:</p>'+
   '<div class="chips"><span class="chip"><b>Important</b> — delivers a highly valued benefit</span><span class="chip"><b>Distinctive</b> — competitors don’t offer it, or not this way</span><span class="chip"><b>Superior</b> — to other ways of getting the benefit</span><span class="chip"><b>Communicable</b> — and visible to buyers</span><span class="chip"><b>Preemptive</b> — not easily copied</span><span class="chip"><b>Affordable</b> — buyers can pay for it</span><span class="chip"><b>Profitable</b> — the company can introduce it profitably</span></div>'+
   '<h3 class="sub" id="c7-value">Figure 7.4 · Possible value propositions</h3>'+
   '<p>The <b>value proposition</b> is the full mix of benefits on which a brand is differentiated and positioned — the answer to the customer’s question, <b>“Why should I buy your brand?”</b> A luxury car’s proposition hinges on performance but includes luxury and styling at a price that is higher than average but seems fair. The figure sorts propositions by benefits (more, the same, less) against price (more, the same, less).</p>'+
   '<div class="vp"><div class="mx-corner"></div><div class="mx-h">Price: more</div><div class="mx-h">Price: the same</div><div class="mx-h">Price: less</div>'+
   '<div class="mx-v">Benefits: more</div><div class="cell win">More for more<small>winning</small></div><div class="cell win">More for the same<small>winning</small></div><div class="cell win">More for less<small>winning</small></div>'+
   '<div class="mx-v">The same</div><div class="cell lose">The same for more<small>losing</small></div><div class="cell meh">The same for the same<small>marginal</small></div><div class="cell win">The same for less<small>winning</small></div>'+
   '<div class="mx-v">Less</div><div class="cell lose">Less for more<small>losing</small></div><div class="cell lose">Less for the same<small>losing</small></div><div class="cell win">Less for much less<small>winning</small></div></div>'+
   '<ul><li><b>More for more</b> — the most upscale product at a higher price. Profitable but vulnerable: it invites imitators claiming the same quality for less.</li><li><b>More for the same</b> — attack a more-for-more competitor with comparable quality at a lower price. Lexus versus Mercedes and BMW.</li><li><b>The same for less</b> — everyone likes a good deal: the same brands as everyone else, cheaper, through low costs and buying power. Walmart; category killers in electronics, pet supplies or shoes.</li><li><b>Less for much less</b> — few people need or can afford the very best in everything; a stripped-down offer at a much lower price. Dollar stores; no-frills airlines.</li><li><b>More for less</b> — the winning proposition everyone claims; achievable in the short run, but offering more usually costs more, so it is hard to sustain.</li></ul>'+
   '<p>In any market there is room for many companies, each occupying a different position; each must find the positioning that makes it special to its target consumers.</p>'+
   '<h3 class="sub" id="c7-statement">The positioning statement, and delivering the position</h3>'+
   '<div class="quote">To (target segment and need) our (brand) is (concept) that (point of difference).<small>The form of a positioning statement</small></div>'+
   '<p>The statement first says who the brand is for and what they need, then the category the brand belongs to, then what sets it apart. For example: <i>To college students who need a good meal between classes, Campus Fresh is a delivery service that brings a hot, healthy lunch to any building on campus in under fifteen minutes.</i> The case for the brand’s superiority is made on its <b>points of difference</b> — a postal service ships packages like its rivals but differentiates its priority mail with convenient, low-price, flat-rate boxes: “If it fits, it ships.”</p>'+
   '<h3>Communicating and delivering the chosen position</h3>'+
   '<ul><li>Choosing the positioning is often easier than implementing it. All the marketing-mix efforts must support the strategy — concrete action, not just talk. A “more for more” position needs a high-quality product, a high price, upscale dealers and upscale advertising.</li><li>Establishing or changing a position usually takes a long time; maintaining it requires consistent performance and communication.</li><li>Monitor and adapt over time, but avoid abrupt changes that confuse consumers.</li></ul>'}
 ],
 decks:[
  {id:"terms", label:"Key terms", cards:[
   ["Market segmentation","Dividing a market into smaller segments with distinct needs, characteristics or behaviors that might require separate strategies or mixes","g7-strategy"],
   ["Market targeting","Evaluating each segment’s attractiveness and selecting one or more segments to enter","g7-strategy"],
   ["Differentiation","Making the market offering different to create superior customer value","g7-strategy"],
   ["Positioning","Arranging for a market offering to occupy a clear, distinctive and desirable place in the minds of target customers","g7-strategy"],
   ["Geographic segmentation","Dividing a market into units such as nations, regions, states, counties, cities or neighborhoods","g7-seg"],
   ["Demographic segmentation","Dividing a market by age, life-cycle stage, gender, income, occupation, education, religion, ethnicity, generation","g7-seg"],
   ["Age and life-cycle segmentation","Dividing a market into different age and life-cycle groups","g7-seg"],
   ["Gender segmentation","Dividing a market into segments based on gender","g7-seg"],
   ["Income segmentation","Dividing a market into different income segments","g7-seg"],
   ["Psychographic segmentation","Dividing a market by social class, lifestyle or personality characteristics","g7-seg"],
   ["Behavioral segmentation","Dividing a market by consumer knowledge, attitudes, uses of a product or responses to it","g7-seg"],
   ["Occasion segmentation","Grouping buyers by when they get the idea to buy, actually buy, or use the product","g7-seg"],
   ["Benefit segmentation","Grouping buyers by the different benefits they seek from a product","g7-seg"],
   ["User status","Nonusers, ex-users, potential users, first-time users, regular users","g7-seg"],
   ["Usage rate","Light, medium and heavy product users","g7-seg"],
   ["Loyalty status","Completely loyal, somewhat loyal, not loyal at all","g7-seg"],
   ["Target market","A set of buyers who share common needs or characteristics that the company decides to serve","g7-target"],
   ["Undifferentiated (mass) marketing","Ignoring segment differences and going after the whole market with one offer","g7-target"],
   ["Differentiated (segmented) marketing","Targeting several segments and designing separate offers for each","g7-target"],
   ["Concentrated (niche) marketing","Going after a large share of one or a few smaller segments","g7-target"],
   ["Micromarketing","Tailoring products and programs to the tastes of specific individuals and locations","g7-target"],
   ["Local marketing","Tailoring brands and promotions to local customer groups — cities, neighborhoods, stores","g7-target"],
   ["Individual marketing","Tailoring products and programs to individual customers — one-to-one, mass customization","g7-target"],
   ["Mass customization","Interacting one-to-one with masses of customers to design tailor-made products and services","g7-target"],
   ["Product position","The way a product is defined by consumers on important attributes — its place in their minds","g7-position"],
   ["Competitive advantage","An advantage over competitors gained by offering greater value — lower prices or more benefits that justify higher prices","g7-position"],
   ["Value proposition","The full mix of benefits on which a brand is differentiated and positioned","g7-position"],
   ["Positioning statement","To (target segment and need) our (brand) is (concept) that (point of difference)","g7-position"]]},
  {id:"lists", label:"Lists & frameworks", cards:[
   ["The four steps of a customer-driven strategy","Segmentation, targeting, differentiation, positioning","g7-strategy"],
   ["The two questions marketing boils down to","Which customers will we serve? How will we serve them?","g7-strategy"],
   ["Which steps answer which question","Segmentation and targeting → which customers; differentiation and positioning → how (the value proposition)","g7-strategy"],
   ["Why segment at all","Buyers differ in wants, resources, locations, attitudes and practices; smaller groups can be served more efficiently and effectively","g7-seg"],
   ["The four bases for segmenting consumer markets","Geographic, demographic, psychographic, behavioral","g7-seg"],
   ["The most popular segmentation bases","Demographic — easier to measure than most variables","g7-seg"],
   ["The best starting point for segments, per many marketers","Behavioral variables","g7-seg"],
   ["The five behavioral bases","Occasions, benefits sought, user status, usage rate, loyalty status","g7-seg"],
   ["Requirements for effective segmentation","Measurable, accessible, substantial, differentiable, actionable","g7-seg"],
   ["How to evaluate a segment","Size and growth, structural attractiveness, company objectives and resources","g7-target"],
   ["What makes a segment structurally unattractive","Strong competitors, easy entry, substitutes, powerful buyers, powerful suppliers","g7-target"],
   ["The four targeting strategies, broad to narrow","Undifferentiated, differentiated, concentrated, micromarketing","g7-target"],
   ["The two kinds of micromarketing","Local marketing and individual marketing","g7-target"],
   ["Five factors in choosing a targeting strategy","Company resources, product variability, life-cycle stage, market variability, competitors’ strategies","g7-target"],
   ["The four steps to a positioning strategy","Identify possible competitive advantages; choose the right ones; select an overall strategy; communicate and deliver the position","g7-position"],
   ["Five ways to differentiate","Product, services, channels, people, image","g7-position"],
   ["Seven criteria for a worthwhile difference","Important, distinctive, superior, communicable, preemptive, affordable, profitable","g7-position"],
   ["The question a value proposition answers","“Why should I buy your brand?”","g7-position"],
   ["The five winning value propositions","More for more, more for the same, more for less, the same for less, less for much less","g7-position"],
   ["The losing value propositions","The same for more, less for more, less for the same","g7-position"],
   ["Products vs brands","Products are made in factories; brands happen in the minds of consumers","g7-position"]]}
 ]
};

QB = QB.concat([
 {tp:"c7",sec:"g7-strategy",t:"mc",q:"The four major steps in designing a customer-driven marketing strategy are:",a:"segmentation, targeting, differentiation, positioning",w:["product, price, place, promotion","awareness, interest, trial, adoption","analysis, planning, implementation, control"],e:"STP — plus differentiation."},
 {tp:"c7",sec:"g7-strategy",t:"mc",q:"Which two steps answer “which customers will we serve?”",a:"Segmentation and targeting",w:["Differentiation and positioning","Targeting and positioning","Segmentation and differentiation"],e:"Segmentation and targeting select customers; differentiation and positioning decide the value proposition."},
 {tp:"c7",sec:"g7-strategy",t:"mc",q:"In Figure 7.1, differentiation and positioning together decide the company’s:",a:"value proposition",w:["target market","segmentation bases","marketing mix"],e:"Segmentation and targeting select customers; differentiation and positioning decide on a value proposition."},
 {tp:"c7",sec:"g7-strategy",t:"mc",q:"Target marketing means:",a:"identifying market segments, selecting one or more, and developing products and programs tailored to each",w:["designing one product for the largest number of buyers","advertising to everyone at once","letting consumers position products on their own"],e:"Most companies have moved from mass marketing to target marketing."},
 {tp:"c7",sec:"g7-strategy",t:"mc",q:"Why can’t a company simply appeal to all buyers in the same way?",a:"Buyers are too numerous, too scattered and too varied in their needs and buying practices",w:["Advertising to everyone is illegal","Most buyers do not have needs","Competitors already own every buyer"],e:"So companies pick the segments they can serve best."},
 {tp:"c7",sec:"g7-strategy",t:"mc",q:"What sits at the center of Figure 7.1?",a:"Create value for targeted customers",w:["Maximize sales volume","Beat competitors on price","Reach the whole market"],e:"Every step exists to create more value for the chosen customers than competitors do."},
 {tp:"c7",sec:"g7-strategy",t:"mc",q:"Which step comes first in designing a customer-driven marketing strategy?",a:"Segmentation",w:["Positioning","Differentiation","Promotion"],e:"A company must know whom it will serve before deciding how to stand out for them."},
 {tp:"c7",sec:"g7-strategy",ap:true,t:"mc",q:"A company has decided which segments to enter and now works on what it will promise them and how it will stand apart. That second job is:",a:"differentiation and positioning — deciding on a value proposition",w:["segmentation and targeting — selecting customers","market research","mass marketing"],e:"How will we serve them?"},
 {tp:"c7",sec:"g7-strategy",t:"tf",q:"Most companies have moved away from mass marketing toward target marketing.",a:true,e:"True."},
 {tp:"c7",sec:"g7-strategy",t:"tf",q:"Differentiation and positioning answer the question of how the company will serve its chosen customers.",a:true,e:"True — they decide the value proposition."},

 {tp:"c7",sec:"g7-seg",t:"mc",q:"Dividing a market into smaller segments with distinct needs, characteristics or behaviors is:",a:"market segmentation",w:["market targeting","positioning","micromarketing"],e:"Segmentation."},
 {tp:"c7",sec:"g7-seg",t:"mc",q:"Why do companies segment markets?",a:"Buyers differ in wants, resources, locations and buying practices, so smaller groups can be served more efficiently and effectively",w:["To raise prices for everyone","Because the law requires it","To avoid doing marketing research"],e:"Products and services matched to each group’s needs."},
 {tp:"c7",sec:"g7-seg",t:"mc",q:"Which segmentation base is the most popular, partly because it is the easiest to measure?",a:"Demographic",w:["Psychographic","Behavioral","Geographic"],e:"Demographic — and even other bases need demographics to size and reach the target."},
 {tp:"c7",sec:"g7-seg",t:"mc",q:"Dividing a market by social class, lifestyle or personality is:",a:"psychographic segmentation",w:["demographic segmentation","behavioral segmentation","geographic segmentation"],e:"Psychographic."},
 {tp:"c7",sec:"g7-seg",t:"mc",q:"Advertising soup more heavily in winter is an example of:",a:"occasion segmentation",w:["benefit segmentation","usage-rate segmentation","loyalty segmentation"],e:"Occasions — when consumers buy or use the product."},
 {tp:"c7",sec:"g7-seg",t:"mc",q:"A bike maker building a different bike for every reason people ride is an example of:",a:"benefit segmentation",w:["occasion segmentation","income segmentation","geographic segmentation"],e:"Benefits sought."},
 {tp:"c7",sec:"g7-seg",t:"mc",q:"Nonusers, ex-users, potential users, first-time users and regular users describe:",a:"user status",w:["usage rate","loyalty status","occasions"],e:"User status."},
 {tp:"c7",sec:"g7-seg",t:"mc",q:"Which segmentation base do many marketers consider the best starting point?",a:"Behavioral",w:["Demographic","Geographic","Psychographic"],e:"Behavior variables — what people actually do with the product."},
 {tp:"c7",sec:"g7-seg",t:"mc",q:"Why do marketers usually combine several segmentation bases?",a:"To identify smaller, better-defined groups they can understand, reach and tailor offers to",w:["Because one base is never legal","To make the market larger","Because demographics cannot be measured"],e:"Commercial systems blend demographics, lifestyle and behavior."},
 {tp:"c7",sec:"g7-seg",t:"mc",q:"A segment whose size, purchasing power and profiles can be measured is:",a:"measurable",w:["accessible","substantial","actionable"],e:"Measurable, accessible, substantial, differentiable, actionable."},
 {tp:"c7",sec:"g7-seg",t:"mc",q:"A segment that responds differently to marketing mix elements is:",a:"differentiable",w:["substantial","accessible","measurable"],e:"Differentiable."},
 {tp:"c7",sec:"g7-seg",t:"mc",q:"A segment profitable enough to serve is:",a:"substantial",w:["actionable","accessible","differentiable"],e:"Substantial."},
 {tp:"c7",sec:"g7-seg",ap:true,t:"mc",q:"A small share of a store’s shoppers buys most of its seafood. The store is segmenting by:",a:"usage rate",w:["user status","benefits sought","occasion"],e:"Heavy users — a small share of buyers, a large share of consumption."},
 {tp:"c7",sec:"g7-seg",ap:true,t:"mc",q:"A gym learns that most of its revenue comes from a small group who visit daily. Which behavioral variable is it looking at?",a:"Usage rate",w:["User status","Occasions","Benefits sought"],e:"Heavy users."},
 {tp:"c7",sec:"g7-seg",ap:true,t:"mc",q:"A ski resort runs most of its lift-ticket promotions in November. Which base is it using?",a:"Occasion",w:["Benefit","Loyalty status","Income"],e:"When consumers get the idea to buy or use the product."},
 {tp:"c7",sec:"g7-seg",ap:true,t:"mc",q:"A toothpaste maker finds some buyers want whitening, others cavity protection, others fresh breath — and makes a version for each. Which base?",a:"Benefits sought",w:["Occasions","User status","Geographic"],e:"Benefit segmentation — the classic toothpaste example."},
 {tp:"c7",sec:"g7-seg",ap:true,t:"mc",q:"An airline gives its most frequent flyers special status and perks. Which behavioral variable is it using?",a:"Loyalty status",w:["Occasions","Benefits sought","Life-cycle stage"],e:"Rewarding the completely loyal — and tempting the somewhat loyal to switch."},
 {tp:"c7",sec:"g7-seg",ap:true,t:"mc",q:"Two coffee chains sell to people of the same age and income, but one attracts the no-nonsense “average Joe” and the other the connoisseur. The difference between their customers is:",a:"psychographic",w:["demographic","geographic","occasion-based"],e:"Same demographics, different lifestyles and personalities."},
 {tp:"c7",sec:"g7-seg",ap:true,t:"mc",q:"A company finds a segment it likes but cannot reach it with any medium or channel. Which requirement fails?",a:"Accessible",w:["Measurable","Substantial","Differentiable"],e:"It cannot be effectively reached and served."},
 {tp:"c7",sec:"g7-seg",ap:true,t:"mc",q:"A company can identify and reach a segment, but it is too small to serve at a profit. Which requirement fails?",a:"Substantial",w:["Measurable","Accessible","Actionable"],e:"Large or profitable enough to serve."},
 {tp:"c7",sec:"g7-seg",ap:true,t:"mc",q:"Two proposed segments turn out to respond exactly the same way to every offer and message. Which requirement fails?",a:"Differentiable",w:["Measurable","Substantial","Accessible"],e:"If they respond the same way, they are really one segment."},
 {tp:"c7",sec:"g7-seg",ap:true,t:"mc",q:"A small airline identifies seven attractive segments but its staff is too small to develop a separate program for each. Which requirement fails?",a:"Actionable",w:["Measurable","Substantial","Differentiable"],e:"Effective programs must be designable and executable for the segments."},
 {tp:"c7",sec:"g7-seg",t:"tf",q:"People in the same demographic group can have very different psychographic characteristics.",a:true,e:"True."},
 {tp:"c7",sec:"g7-seg",t:"tf",q:"Segments defined by behavior or benefits still need demographics to estimate their size and reach them.",a:true,e:"True — which is one reason demographics are the most popular base."},

 {tp:"c7",sec:"g7-target",t:"mc",q:"Which is NOT one of the three things a company evaluates in a segment?",a:"The segment’s brand personality",w:["Size and growth","Structural attractiveness","Company objectives and resources"],e:"Size and growth; structural attractiveness; objectives and resources."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"Which of these makes a segment LESS structurally attractive?",a:"Many substitute products that limit the prices the segment will pay",w:["High barriers to entry","Weak, passive competitors","Buyers with little bargaining power"],e:"Strong competitors, easy entry, substitutes, powerful buyers and powerful suppliers all reduce attractiveness."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"Targeting the whole market with one offer, focusing on common needs, is:",a:"undifferentiated (mass) marketing",w:["differentiated marketing","concentrated marketing","micromarketing"],e:"Undifferentiated — most modern marketers doubt it."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"A hotel company running many brands, each aimed at a different kind of traveler, illustrates:",a:"differentiated marketing",w:["concentrated marketing","undifferentiated marketing","local marketing"],e:"Several segments, a separate offer for each."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"A razor start-up selling direct to one underserved segment illustrates:",a:"concentrated (niche) marketing",w:["differentiated marketing","mass marketing","individual marketing"],e:"A large share of a smaller market."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"A risk of concentrated marketing is that:",a:"the segment may turn sour or a larger competitor may enter it",w:["it is the most expensive strategy","it ignores segment differences","it dilutes the brand’s image"],e:"Relying on one segment is risky — so many companies diversify."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"The main drawback of differentiated marketing is that it:",a:"raises the costs of doing business — separate products, research, promotion and channels for each segment",w:["produces lower total sales","cannot be used by large companies","is illegal in most markets"],e:"Weigh the extra sales against the extra costs."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"Micromarketing includes:",a:"local marketing and individual marketing",w:["mass marketing and niche marketing","differentiated and undifferentiated marketing","benefit and occasion marketing"],e:"Local and individual."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"A car maker designing a car together with each customer is:",a:"individual marketing",w:["local marketing","concentrated marketing","differentiated marketing"],e:"One-to-one — mass customization at the extreme."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"A drawback of local marketing is that it:",a:"drives up costs by reducing economies of scale and can dilute the brand image",w:["ignores local differences","requires a single national offer","cannot use mobile technology"],e:"Costs, logistics, and a diluted image."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"For a uniform product such as grapefruit or steel, the best-suited strategy is:",a:"undifferentiated marketing",w:["concentrated marketing","individual marketing","differentiated marketing"],e:"Low product variability → undifferentiated."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"When a firm’s resources are limited, which strategy makes the most sense?",a:"Concentrated marketing",w:["Differentiated marketing","Undifferentiated marketing","Mass marketing"],e:"Concentrated."},
 {tp:"c7",sec:"g7-target",t:"mc",q:"If competitors are already segmenting the market, undifferentiated marketing:",a:"can be suicidal",w:["is the safest choice","is required by law","always wins on cost"],e:"When competitors segment, a one-offer company loses every segment to a better-fitted rival."},
 {tp:"c7",sec:"g7-target",ap:true,t:"mc",q:"A bakery notices its customers are either health-focused parents or students grabbing a treat, and designs a separate menu and message for each. This is:",a:"differentiated marketing",w:["undifferentiated marketing","concentrated marketing","individual marketing"],e:"Several segments, separate offers."},
 {tp:"c7",sec:"g7-target",ap:true,t:"mc",q:"A coffee shop chain customizes its menu for each neighborhood. This is:",a:"local marketing",w:["individual marketing","concentrated marketing","undifferentiated marketing"],e:"Micromarketing at the local level."},
 {tp:"c7",sec:"g7-target",ap:true,t:"mc",q:"A startup with little money picks one small, underserved segment and serves it well. Its strategy is:",a:"concentrated marketing",w:["differentiated marketing","mass marketing","local marketing"],e:"Limited resources → concentrated."},
 {tp:"c7",sec:"g7-target",ap:true,t:"mc",q:"A steel producer sells one grade of steel to every customer with one price list and one message. Its strategy is:",a:"undifferentiated marketing",w:["differentiated marketing","concentrated marketing","individual marketing"],e:"A uniform product and buyers who react the same way → undifferentiated."},
 {tp:"c7",sec:"g7-target",ap:true,t:"mc",q:"A regional bank considers a segment crowded with aggressive national competitors, where customers can switch freely to online lenders. The segment is unattractive because of its:",a:"structural attractiveness",w:["size and growth","company objectives","segment measurability"],e:"Strong competitors and substitutes cap the profits available."},
 {tp:"c7",sec:"g7-target",ap:true,t:"mc",q:"A candy company launches a new bar in one version, then adds sugar-free and king-size versions as sales mature. Which factor guided the change in strategy?",a:"The product’s life-cycle stage",w:["Company resources","Market variability","Competitors’ strategies"],e:"One version at launch; differentiated marketing in maturity."},
 {tp:"c7",sec:"g7-target",ap:true,t:"mc",q:"A sporting-goods maker finds a large, fast-growing segment, but it lies far outside the company’s long-run objectives and skills. It should:",a:"pass on the segment — attractiveness alone is not enough",w:["enter it because it is growing fast","enter it with undifferentiated marketing","raise prices there"],e:"Enter only segments where the company can create superior value and gain an advantage."},
 {tp:"c7",sec:"g7-target",t:"tf",q:"The largest, fastest-growing segments are always the most attractive for every company.",a:false,e:"False — smaller companies may do better in smaller segments."},
 {tp:"c7",sec:"g7-target",t:"tf",q:"Differentiated marketing is usually less expensive to execute than undifferentiated marketing.",a:false,e:"False — it increases the costs of doing business."},
 {tp:"c7",sec:"g7-target",t:"tf",q:"Micromarketing is the narrowest of the four targeting strategies.",a:true,e:"True — it tailors to individuals and locations."},

 {tp:"c7",sec:"g7-position",t:"mc",q:"The way a product is defined by consumers on important attributes is its:",a:"product position",w:["value proposition","competitive advantage","brand equity"],e:"Position — the place in consumers’ minds."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"“Products are made in factories, but brands happen in the minds of consumers” is about:",a:"positioning",w:["segmentation","targeting","e-procurement"],e:"Positioning."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"A sandwich chain built on “freaky fast” delivery differentiates on:",a:"services",w:["product","channels","image"],e:"Service differentiation — speedy delivery."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"A retailer and an insurer that set themselves apart through smooth direct channels are using:",a:"channel differentiation",w:["people differentiation","product differentiation","image differentiation"],e:"Coverage, expertise and performance of the channel."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"An advantage gained by offering greater value, through lower prices or more benefits that justify higher prices, is:",a:"competitive advantage",w:["product position","market segment","mass customization"],e:"Competitive advantage."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"The first step in choosing a differentiation and positioning strategy is:",a:"identifying a set of possible competitive advantages to build a position on",w:["writing the advertising","selecting an overall positioning strategy","communicating the position"],e:"Identify → choose → select an overall strategy → communicate and deliver."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"A difference that competitors cannot easily copy is:",a:"preemptive",w:["distinctive","superior","communicable"],e:"Preemptive."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"The full mix of benefits on which a brand is positioned is its:",a:"value proposition",w:["product position","segment profile","target market"],e:"The value proposition — “why should I buy your brand?”"},
 {tp:"c7",sec:"g7-position",t:"mc",q:"Toyota introducing Lexus against Mercedes and BMW with comparable quality at a lower price was:",a:"more for the same",w:["more for more","the same for less","less for much less"],e:"More for the same."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"Dollar stores are positioned as:",a:"less for much less",w:["more for less","the same for less","more for the same"],e:"Less for much less."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"Which value proposition is described as vulnerable because it invites imitators?",a:"More for more",w:["The same for less","Less for much less","More for the same"],e:"More for more invites “the same quality at a lower price.”"},
 {tp:"c7",sec:"g7-position",t:"mc",q:"Which value proposition is hard to sustain because offering more usually costs more?",a:"More for less",w:["More for more","Less for much less","The same for less"],e:"More for less — possible for a while, rarely for long."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"A positioning statement takes the form:",a:"To (target segment and need) our (brand) is (concept) that (point of difference)",w:["For (price) we offer (product) with (features)","Our (brand) beats (competitor) on (attribute)","To (everyone) our (brand) is (the best)"],e:"Target, brand, concept, point of difference."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"Two coffee-and-snack chains succeed side by side because:",a:"each creates the right value proposition for its own customers — average Joe vs. upscale destination",w:["they sell identical coffee at identical prices","one of them uses undifferentiated marketing","both target the same upscale professionals"],e:"Different targets, different positioning."},
 {tp:"c7",sec:"g7-position",t:"mc",q:"Why is choosing a position often easier than implementing it?",a:"Every part of the marketing mix has to support the position with concrete action, not just talk",w:["Consumers do not notice positions","Positions cannot be changed once chosen","Advertising is the only tool needed"],e:"A “more for more” position needs the product, price, dealers and advertising to match."},
 {tp:"c7",sec:"g7-position",ap:true,t:"mc",q:"A retailer sells the same jeans as everyone else but for 30% less. Its value proposition is:",a:"the same for less",w:["more for less","less for much less","more for the same"],e:"Same benefits, lower price."},
 {tp:"c7",sec:"g7-position",ap:true,t:"mc",q:"A phone maker charges more than its rivals and offers more features, better design and a premium image. Its value proposition is:",a:"more for more",w:["more for the same","the same for less","less for much less"],e:"The most upscale product at a higher price."},
 {tp:"c7",sec:"g7-position",ap:true,t:"mc",q:"An airline offers fewer amenities — no meals, no assigned seats — for much lower fares. Its value proposition is:",a:"less for much less",w:["the same for less","more for less","more for the same"],e:"A stripped-down offer at a much lower price."},
 {tp:"c7",sec:"g7-position",ap:true,t:"mc",q:"A store hires and trains friendlier, more knowledgeable staff than its competitors. It is differentiating on:",a:"people",w:["product","channels","image"],e:"People differentiation."},
 {tp:"c7",sec:"g7-position",ap:true,t:"mc",q:"A brand builds its identity around a memorable mascot and a distinctive advertising style. It is differentiating on:",a:"image",w:["services","channels","product"],e:"Symbols, characters and image elements that convey the brand’s personality."},
 {tp:"c7",sec:"g7-position",ap:true,t:"mc",q:"A brand promotes a feature that competitors can copy within weeks. Which criterion for a worthwhile difference does it fail?",a:"Preemptive",w:["Important","Affordable","Communicable"],e:"Not easily copied."},
 {tp:"c7",sec:"g7-position",ap:true,t:"mc",q:"A brand’s difference is real but customers cannot see it or understand it. Which criterion does it fail?",a:"Communicable",w:["Distinctive","Superior","Profitable"],e:"Communicable and visible to buyers."},
 {tp:"c7",sec:"g7-position",ap:true,t:"mc",q:"“To college students who need a good meal between classes, Campus Fresh is a delivery service that brings a hot, healthy lunch to any building in under fifteen minutes.” The point of difference is:",a:"a hot, healthy lunch delivered to any building in under fifteen minutes",w:["college students who need a good meal","Campus Fresh","a delivery service"],e:"Target and need → brand → concept (delivery service) → point of difference."},
 {tp:"c7",sec:"g7-position",t:"tf",q:"Consumers position products in their minds with or without the help of marketers.",a:true,e:"True — so marketers plan positions rather than leave them to chance."},
 {tp:"c7",sec:"g7-position",t:"tf",q:"Every brand difference is worth establishing.",a:false,e:"False — each has costs; it must be important, distinctive, superior, communicable, preemptive, affordable and profitable."},
 {tp:"c7",sec:"g7-position",t:"tf",q:"Choosing a position is usually harder than implementing it.",a:false,e:"False — choosing is often easier than implementing."},
 {tp:"c7",sec:"g7-position",t:"tf",q:"Companies should evolve their positioning gradually and avoid abrupt changes that confuse consumers.",a:true,e:"True."},
 {tp:"c7",sec:"g7-position",t:"tf",q:"In any market there is usually room for only one successful position.",a:false,e:"False — many companies can each occupy a different position."}
]);
