/* ================================================================ chapter 8
   Products, Services, and Brands. The four sections are the Exam 2 study
   guide's — which limits Branding Strategy to brand equity and brand value, so
   the rest of branding is not here. Each section explains its point in plain
   terms first, then the concepts; examples stay only where they show one.     */
CH.c8 = {n:8, title:"Products, Services, and Brands: Building Customer Value", short:"Products",
 notes:[
  {id:"c8-what", h:"What is a Product", body:
   '<div class="point"><b>The point</b><p>A product is anything offered to satisfy a need — goods, services, experiences, people, places, ideas. It has three levels: the <b>core benefit</b> the buyer is really after, the <b>actual product</b>, and the <b>augmented</b> extras around it. Products are classified by who buys them (consumer vs industrial) and, for consumers, by how they buy (convenience, shopping, specialty, unsought) — and that classification shapes price, distribution and promotion.</p><p class="able"><b>Be able to</b> name the level a feature belongs to, classify a product, and explain how its classification changes the way it is marketed.</p></div>'+
   '<h3 class="sub" id="c8-levels">Product, service, and the three levels</h3>'+
   '<p class="knowline"><span class="know">Objective 8.1</span></p>'+
   '<p>A <b>product</b> is anything that can be offered in a market for attention, acquisition, use or consumption that might satisfy a need or want — not just cars, computers and phones but services, events, persons, places, organizations, ideas, or a mixture. A <b>service</b> is a product that consists of activities, benefits or satisfactions, essentially intangible, that does not result in the ownership of anything — banking, hotels, airlines, retail, wireless, home repair.</p>'+
   '<p>Products, services and <b>experiences</b>: a sports bar doesn’t just serve wings and beer; it sells the fan experience. Companies that market experiences realize customers are really buying what the offer will do for them.</p>'+
   '<h3>Figure 8.1 · Three levels of product</h3>'+
   '<div class="levels">'+
   '<div class="lv"><b>1 · Core customer value</b><span>What is the buyer <i>really</i> buying? People who buy a tablet are buying entertainment, self-expression, productivity and connectivity — a window to the world. Motorcycle buyers buy freedom, independence, power and authenticity.</span></div>'+
   '<div class="lv"><b>2 · Actual product</b><span>Brand name, features, design, packaging, quality level — the core benefit turned into something you can buy.</span></div>'+
   '<div class="lv"><b>3 · Augmented product</b><span>Delivery and credit, after-sale service, warranty, product support — the extras built around the core and actual product.</span></div></div>'+
   '<p>Each level adds more customer value. When developing a product, marketers first identify the core value, then design the actual product, then find ways to augment it.</p>'+
   '<h3>Core customer value — examples from class</h3>'+
   '<div class="tblwrap"><table class="tbl n0"><tbody>'+
   '<tr><td class="head">A cruise line</td><td class="sm">Fun, indulgent memories — not cabins and buffets</td></tr>'+
   '<tr><td class="head">A financial adviser</td><td class="sm">Financial security and peace of mind — not mutual funds</td></tr>'+
   '<tr><td class="head">A fast-casual restaurant</td><td class="sm">A healthy choice, fast — not burritos</td></tr>'+
   '<tr><td class="head">A luxury watch</td><td class="sm">Status, value and reliability — not telling the time</td></tr>'+
   '</tbody></table></div>'+
   '<h3 class="sub" id="c8-class">Product and service classifications</h3>'+
   '<p>Two broad classes, based on who uses them: <b>consumer products</b> and <b>industrial products</b>. The distinction is the <i>purpose</i>: a lawn mower for home is a consumer product; the same mower bought for a landscaping business is an industrial product.</p>'+
   '<h3>Consumer products — Table 8.1</h3>'+
   '<p>Consumer products are classified by <i>how consumers go about buying them</i>, and each type is marketed differently.</p>'+
   '<div class="tblwrap"><table class="tbl"><thead><tr><th></th><th>Convenience</th><th>Shopping</th><th>Specialty</th><th>Unsought</th></tr></thead><tbody>'+
   '<tr><td class="head">Buying behavior</td><td class="sm">Frequent purchase; little planning, comparison or effort; low involvement</td><td class="sm">Less frequent; much planning and shopping effort; comparison on price, quality, style</td><td class="sm">Strong brand preference and loyalty; special purchase effort; little comparison; low price sensitivity</td><td class="sm">Little awareness or knowledge — or, if aware, little or even negative interest</td></tr>'+
   '<tr><td class="head">Price</td><td class="sm">Low</td><td class="sm">Higher</td><td class="sm">Highest</td><td class="sm">Varies</td></tr>'+
   '<tr><td class="head">Distribution</td><td class="sm">Widespread; convenient locations</td><td class="sm">Selective, fewer outlets</td><td class="sm">Exclusive — one or a few outlets per market area</td><td class="sm">Varies</td></tr>'+
   '<tr><td class="head">Promotion</td><td class="sm">Mass promotion by the producer</td><td class="sm">Advertising and personal selling by producer and resellers</td><td class="sm">More carefully targeted promotion by producer and resellers</td><td class="sm">Aggressive advertising and personal selling</td></tr>'+
   '<tr><td class="head">Examples</td><td class="sm">Toothpaste, magazines, detergent, candy, fast food</td><td class="sm">Appliances, TVs, furniture, clothing, cars, phones and computers</td><td class="sm">Luxury watches, fine crystal, designer clothes, medical specialists, custom-made items</td><td class="sm">Life insurance, blood donations, funeral services</td></tr>'+
   '</tbody></table></div>'+
   '<p class="ask">A puzzle worth thinking through: what product could be convenience, shopping <i>and</i> specialty? A camera — grabbed at a pharmacy on vacation, compared for months by a hobbyist, or a $5,000 tool for a professional. The type depends on how the buyer buys, not on the object.</p>'+
   '<h3>Industrial products</h3>'+
   '<ul><li><b>Materials and parts</b> — raw materials, and manufactured materials and parts; sold mostly on price and service.</li><li><b>Capital items</b> — aid in the buyer’s production or operations: installations (buildings, large equipment) and accessory equipment (tools, office equipment).</li><li><b>Supplies and services</b> — operating supplies, repair and maintenance items, business services; the convenience products of the industrial world.</li></ul>'+
   '<h3>Other marketable entities</h3>'+
   '<ul><li><b>Organization marketing</b> — creating, maintaining or changing attitudes and behavior toward an organization (corporate image campaigns).</li><li><b>Person marketing</b> — toward particular people: politicians, entertainers, athletes, doctors, lawyers.</li><li><b>Place marketing</b> — toward places: cities, states and nations competing for tourists, residents and businesses.</li><li><b>Social marketing</b> — using commercial marketing concepts to influence behavior that improves individual and social well-being: anti-smoking, safe driving, recycling.</li></ul>'},
  {id:"c8-decisions", h:"Product and Service Decisions", body:
   '<div class="point"><b>The point</b><p>Building a product means deciding its <b>attributes</b> (quality, features, style and design), its <b>branding</b>, <b>packaging</b>, <b>labeling</b> and <b>support services</b>; then managing the <b>product line</b> (how long, whether to stretch or fill it) and the whole <b>product mix</b> (width, length, depth, consistency).</p><p class="able"><b>Be able to</b> tell performance from conformance quality, style from design, and line stretching from line filling — and name which mix dimension changes in a scenario.</p></div>'+
   '<h3 class="sub" id="c8-attributes">Individual product and service decisions</h3>'+
   '<p class="knowline"><span class="know">Objective 8.2</span></p>'+
   '<p>Developing a product means defining the benefits it will offer, communicated and delivered through <b>product attributes</b>: quality, features, style and design. Then branding, packaging, labeling and support services.</p>'+
   '<h3>Product quality</h3>'+
   '<p>The characteristics of a product or service that bear on its ability to satisfy stated or implied customer needs. Narrowly, “freedom from defects”; most marketers define it by customer value and satisfaction. <b>Total quality management</b> involves everyone in constantly improving quality; today’s <b>return-on-quality</b> approach treats quality as an investment accountable for results. Two dimensions: <b>quality level</b> — <b>performance quality</b>, the ability to perform its functions, chosen to support the product’s positioning (few companies aim for the highest possible level; they aim for the level their target market wants) — and consistency — <b>conformance quality</b>, freedom from defects and consistent delivery of the targeted performance, which every company should strive for. Quality is one of the marketer’s major positioning tools.</p>'+
   '<h3>Features</h3><p>A competitive tool for differentiating from competitors; a stripped-down model is the starting point and higher-level models add features. Being first with a valued new feature is one of the most effective ways to compete. Survey users — what do you like, which features, what could we add — then assess each feature’s <b>value to the customer versus its cost to the company</b>; features customers value little relative to their cost are dropped.</p>'+
   '<h3>Style and design</h3><p><b>Style</b> describes appearance — it can grab attention, but it does not necessarily make the product perform better. <b>Design</b> contributes to usefulness as well as looks — a larger concept. Good design doesn’t start with brainstorming and prototypes; it begins with <b>observing customers, understanding their needs, and shaping their product-use experience</b>.</p>'+
   '<h3>Branding</h3><p>A <b>brand</b> is a name, term, sign, symbol or design, or a combination, that identifies the maker or seller of a product or service. Brands help consumers identify products and say something about quality and consistency — buyers who always buy the same brand know they will get the same features and quality each time; for the seller they give legal protection, help segment markets, and communicate features. The name on a product changes how much people will pay for it — which is the subject of the branding section.</p>'+
   '<h3>Packaging and labeling</h3><p><b>Packaging</b> — designing and producing the container or wrapper, now including “smart packaging.” Once its job was to hold and protect; now it is prime marketing space, a way to stand out on a crowded shelf. <b>Labels</b> identify the product or brand, describe it (who made it, where, when, contents, how to use it safely), and promote the brand.</p>'+
   '<h3>Product support services</h3><p>Support services augment actual products. Keeping customers happy after the sale is the key to lasting relationships: a car maker that promises to treat each customer “as a guest in our home” and backs it with after-sale service is competing on support, not just on the car.</p>'+
   '<h3 class="sub" id="c8-lines">Product lines and the product mix</h3>'+
   '<p>A <b>product line</b> is a group of products that are closely related because they function in a similar manner, are sold to the same customer groups, are marketed through the same outlets, or fall within given price ranges. The major decision is <b>line length</b>: too short if adding items would raise profits, too long if dropping items would.</p>'+
   '<ul><li><b>Line stretching</b> — lengthening the line beyond its current range: downward (a lower-priced model to reach new buyers), upward (a premium model), or both ways; the same brand name carries the new item.</li><li><b>Line filling</b> — adding new items within the line’s present range so there are no gaps for competitors to move into — a car maker filling every size and price step from its smallest sedan to its largest, hoping to move customers up the line over the years.</li></ul>'+
   '<h3>The product mix</h3>'+
   '<p>The <b>product mix</b> (product portfolio) is all the product lines and items a seller offers.</p>'+
   '<div class="tblwrap"><table class="tbl n0"><tbody>'+
   '<tr><td class="head">Width</td><td class="sm">The number of different product lines. A coffee chain’s mix: coffee, tumblers, food, brewing equipment — four lines.</td></tr>'+
   '<tr><td class="head">Length</td><td class="sm">The total number of items in all lines.</td></tr>'+
   '<tr><td class="head">Depth</td><td class="sm">The number of versions of each product in the line — iced coffee, latte, frappuccino, espresso.</td></tr>'+
   '<tr><td class="head">Consistency</td><td class="sm">How closely the lines are related in end use, production requirements or distribution channels.</td></tr>'+
   '</tbody></table></div>'+
   '<p>These dimensions are the handles for defining product strategy: add lines (width), lengthen lines, deepen them with versions, or pursue more or less consistency. From time to time a company streamlines its mix to drop marginal lines and regain focus.</p>'},
  {id:"c8-services", h:"Services Marketing", body:
   '<div class="point"><b>The point</b><p>Services are <b>intangible</b>, <b>inseparable</b> from their providers, <b>variable</b> in quality and <b>perishable</b>, so marketing them means managing employees and service encounters, not just advertising. The <b>service-profit chain</b> links happy, productive employees to satisfied, loyal customers to profit — through internal and interactive marketing on top of the usual external marketing.</p><p class="able"><b>Be able to</b> identify the characteristic in a scenario, order the links of the service-profit chain, and distinguish internal, interactive and external marketing.</p></div>'+
   '<h3 class="sub" id="c8-four">Figure 8.3 · Four service characteristics</h3>'+
   '<p class="knowline"><span class="know">Objective 8.3</span></p>'+
   '<div class="boxrow four"><div class="box"><h4>Intangibility</h4><p>Services cannot be seen, tasted, felt, heard or smelled before purchase — so buyers look for signals of quality: the place, the people, the equipment, the price.</p></div>'+
   '<div class="box"><h4>Inseparability</h4><p>Services cannot be separated from their providers — the provider is part of the service, and so is the customer.</p></div>'+
   '<div class="box"><h4>Variability</h4><p>Quality depends on who provides them and when, where and how — so firms select and train people carefully.</p></div>'+
   '<div class="box"><h4>Perishability</h4><p>Services cannot be stored for later sale or use — an empty seat or an idle hour is lost; firms manage demand with pricing and staffing.</p></div></div>'+
   '<p>The biggest differences come from services being intangible and created through direct interaction with customers — think of an airline or a search engine versus a shoe or a phone.</p>'+
   '<h3 class="sub" id="c8-chain">The service-profit chain</h3>'+
   '<p>In a service business the customer and the front-line employee interact to create the service, so profits start with the people who deliver it. The chain links service-firm profits with employee and customer satisfaction:</p>'+
   '<div class="flow"><div class="step"><b>1</b>Internal service quality — superior employee selection and training, a quality work environment, strong support.</div><div class="step"><b>2</b>Satisfied and productive service employees.</div><div class="step"><b>3</b>Greater service value — more effective and efficient value creation and delivery.</div><div class="step"><b>4</b>Satisfied and loyal customers — repeat purchases and referrals.</div><div class="step"><b>5</b>Healthy service profits and growth.</div></div>'+
   '<p>Reaching service profit goals therefore begins with taking care of the people who take care of customers. Good service firms position themselves as strongly as goods firms do — “faster, farther,” “reviews you can trust,” “we love having you here.”</p>'+
   '<h3 class="sub" id="c8-three">Three kinds of service marketing</h3>'+
   '<ul><li><b>Internal marketing</b> — orienting and motivating customer-contact employees and support people to work as a team for customer satisfaction. Everyone must be customer centered; internal marketing must <b>precede</b> external marketing, because it makes no sense to advertise excellent service before the staff is ready to provide it.</li><li><b>Interactive marketing</b> — service quality depends heavily on the buyer–seller interaction during the service encounter, so the provider’s skill and manner are the marketing: a luxury hotel selects people with an innate “passion to serve” and trains them for months.</li><li>Plus the traditional <b>external marketing</b> mix — the four Ps aimed at customers.</li></ul>'+
   '<h3>Three service tasks</h3>'+
   '<ul><li><b>Service differentiation</b> — through the offer, the delivery, or the image.</li><li><b>Service quality</b> — harder to define and judge than product quality; <b>customer retention is perhaps the best measure</b>, since customers stay with a service that meets their expectations. Is it a competitive advantage?</li><li><b>Service productivity</b> — developing and managing staff; but not at the expense of quality.</li></ul>'+
   '<p>In service marketing it is nearly impossible to separate the person providing the service from the service itself — the provider becomes the image of the firm.</p>'},
  {id:"c8-brands", h:"Branding Strategy: Brand Equity and Brand Value", body:
   '<div class="point"><b>The point</b><p><b>Brand equity</b> is the extra pull a name has on customers — they respond better to it than to an unbranded product — built on differentiation, relevance, knowledge and esteem, and resting on the customer relationships the brand creates. <b>Brand value</b> is that pull turned into dollars: the brand’s estimated financial worth, which is hard to measure exactly.</p><p class="able"><b>Be able to</b> define both, tell them apart, and list what high brand equity buys a company.</p></div>'+
   '<p class="knowline"><span class="know">Objective 8.4 — the study guide asks for brand equity and brand value only</span></p>'+
   '<p>Brands are more than names and symbols: they represent consumers’ perceptions and feelings about a product and its performance — everything it means to them. Brands exist in the heads of consumers. A brand also facilitates the purchase decision as a <b>“short-cut”</b>: the name tells the buyer what to expect.</p>'+
   '<h3 class="sub" id="c8-equity">Brand equity</h3>'+
   '<ul><li><b>Brand equity</b> is the differential effect that knowing the brand name has on customer response to the product or its marketing. Positive equity: consumers react more favorably than to a generic or unbranded product — they will pay more, or choose it first. Negative equity: they react less favorably. The class’s shorthand: the brand is <b>“top of mind”</b> — the first one customers think of.</li><li>Young &amp; Rubicam’s <b>BrandAsset Valuator</b> measures strength on four dimensions: <b>differentiation</b> (what makes the brand stand out), <b>relevance</b> (how consumers feel it meets their needs), <b>knowledge</b> (how much they know about it) and <b>esteem</b> (how highly they regard it). Brands with strong equity rate high on all four; positive equity comes from consumer feelings and connections, and strong brands are built around an ideal of improving consumers’ lives.</li><li>High equity brings a high level of consumer awareness and loyalty, more leverage in bargaining with resellers, easier launch of line and brand extensions, and a defense against fierce price competition.</li><li>The fundamental asset underneath is <b>customer equity</b> — the value of the customer relationships the brand creates. A powerful brand is important, but what it really represents is a set of loyal customers. Companies should think of themselves as portfolios of customers, not portfolios of brands.</li></ul>'+
   '<h3 class="sub" id="c8-value">Brand value</h3>'+
   '<p><b>Brand value</b> is the total financial value of a brand — what the brand would be worth as an asset — and brand valuation is the process of estimating it. Measuring it is difficult: valuation firms combine a brand’s financial performance, its role in customers’ purchase decisions and its strength in their minds, and because each firm weighs those differently, their rankings of the world’s most valuable brands disagree. What they agree on is that the strongest brands are worth many billions — a great brand is a company’s most enduring asset, outlasting its products and facilities.</p>'+
   '<div class="exam-tip"><b>Equity versus value</b>Brand equity is about the customer’s response (the pull of the name); brand value is about money (what that pull is worth). High equity is what produces high value.</div>'}
 ],
 decks:[
  {id:"terms", label:"Key terms", cards:[
   ["Product","Anything offered in a market for attention, acquisition, use or consumption that might satisfy a need or want","g8-what"],
   ["Service","A product consisting of activities, benefits or satisfactions — essentially intangible, no ownership results","g8-what"],
   ["Core customer value","The first level of a product: what the buyer is really buying","g8-what"],
   ["Actual product","The second level: brand name, features, design, packaging, quality level","g8-what"],
   ["Augmented product","The third level: delivery and credit, after-sale service, warranty, product support","g8-what"],
   ["Consumer product","A product or service bought by final consumers for personal consumption","g8-what"],
   ["Industrial product","A product purchased for further processing or for use in conducting a business","g8-what"],
   ["Convenience product","Bought frequently, immediately, with minimal comparison and effort — low price, widespread distribution","g8-what"],
   ["Shopping product","Bought less frequently; compared carefully on suitability, quality, price and style","g8-what"],
   ["Specialty product","Unique characteristics or brand identification for which buyers make a special purchase effort","g8-what"],
   ["Unsought product","A product the consumer doesn’t know about, or knows about but doesn’t normally think of buying","g8-what"],
   ["Organization marketing","Activities to create, maintain or change attitudes and behavior toward an organization","g8-what"],
   ["Person marketing","Activities to create, maintain or change attitudes or behavior toward particular people","g8-what"],
   ["Place marketing","Activities to create, maintain or change attitudes and behavior toward particular places","g8-what"],
   ["Social marketing","Using commercial marketing concepts to influence behavior that improves well-being","g8-what"],
   ["Product quality","The characteristics of a product or service that bear on its ability to satisfy stated or implied needs","g8-decisions"],
   ["Total quality management","All the company’s people constantly improving the quality of products, services and processes","g8-decisions"],
   ["Return-on-quality","Viewing quality as an investment and holding quality efforts accountable for results","g8-decisions"],
   ["Performance quality","The product’s ability to perform its functions — the quality level","g8-decisions"],
   ["Conformance quality","Freedom from defects and consistency in delivering a targeted level of performance","g8-decisions"],
   ["Style","The appearance of a product","g8-decisions"],
   ["Design","Contributes to a product’s usefulness as well as its looks — a larger concept than style","g8-decisions"],
   ["Brand","A name, term, sign, symbol or design that identifies the maker or seller of a product or service","g8-decisions"],
   ["Packaging","Designing and producing the container or wrapper for a product","g8-decisions"],
   ["Product line","A group of products closely related by function, customers, outlets or price range","g8-decisions"],
   ["Product mix (portfolio)","All the product lines and items a particular seller offers for sale","g8-decisions"],
   ["Line stretching","Lengthening a product line beyond its current range — downward, upward or both","g8-decisions"],
   ["Line filling","Adding items within a line’s present range so there are no gaps for competitors","g8-decisions"],
   ["Service intangibility","Services cannot be seen, tasted, felt, heard or smelled before they are bought","g8-services"],
   ["Service inseparability","Services cannot be separated from their providers","g8-services"],
   ["Service variability","Service quality depends on who provides it and when, where and how","g8-services"],
   ["Service perishability","Services cannot be stored for later sale or use","g8-services"],
   ["Service-profit chain","The chain linking service-firm profits with employee and customer satisfaction","g8-services"],
   ["Internal marketing","Orienting and motivating customer-contact and support employees to work as a team for satisfaction","g8-services"],
   ["Interactive marketing","Service quality depends heavily on the buyer–seller interaction during the service encounter","g8-services"],
   ["Brand equity","The differential effect that knowing the brand name has on customer response to the product or its marketing","g8-brands"],
   ["Brand value","The total financial value of a brand","g8-brands"],
   ["Customer equity","The value of the customer relationships that the brand creates","g8-brands"]]},
  {id:"lists", label:"Lists & frameworks", cards:[
   ["The three levels of product","Core customer value, actual product, augmented product","g8-what"],
   ["The actual product’s five parts","Brand name, features, design, packaging, quality level","g8-what"],
   ["The augmented product’s four parts","Delivery and credit, after-sale service, warranty, product support","g8-what"],
   ["What decides consumer vs industrial","The purpose the buyer has — the same mower is consumer at home and industrial for a landscaper","g8-what"],
   ["The four consumer product types","Convenience, shopping, specialty, unsought","g8-what"],
   ["What decides the consumer product type","How the consumer buys it — the same camera can be convenience, shopping or specialty","g8-what"],
   ["The three industrial product groups","Materials and parts, capital items, supplies and services","g8-what"],
   ["Product attributes","Quality, features, style and design","g8-decisions"],
   ["Two dimensions of quality","Level (performance quality) and consistency (conformance quality)","g8-decisions"],
   ["Line stretching vs line filling","Stretching goes beyond the line’s current range; filling adds items within it","g8-decisions"],
   ["The four product-mix dimensions","Width, length, depth, consistency","g8-decisions"],
   ["What each mix dimension counts","Width = lines; length = all items; depth = versions of each product; consistency = how related the lines are","g8-decisions"],
   ["The four service characteristics","Intangibility, inseparability, variability, perishability","g8-services"],
   ["The service-profit chain’s five links","Internal service quality → satisfied, productive employees → greater service value → satisfied, loyal customers → healthy profits and growth","g8-services"],
   ["Three kinds of service marketing","Internal, interactive, external","g8-services"],
   ["Three service tasks","Service differentiation, service quality, service productivity","g8-services"],
   ["Best measure of service quality","Customer retention","g8-services"],
   ["BrandAsset Valuator dimensions","Differentiation, relevance, knowledge, esteem","g8-brands"],
   ["Four advantages of high brand equity","Awareness and loyalty; leverage with resellers; easier extensions; defense against price competition","g8-brands"],
   ["Brand equity vs brand value","Equity = the differential effect of the name on customer response; value = the brand’s total financial worth","g8-brands"],
   ["The asset underneath brand equity","Customer equity — the value of the customer relationships the brand creates","g8-brands"]]}
 ]
};

QB = QB.concat([
 {tp:"c8",sec:"g8-what",t:"mc",q:"A product is anything that can be offered in a market for:",a:"attention, acquisition, use or consumption that might satisfy a need or want",w:["sale at a profit to a buyer willing to pay more than it cost to make","manufacture in a factory and distribution through wholesalers and retailers","resale by intermediaries who add a margin before passing it to consumers"],e:"Broadly defined — services, events, persons, places, organizations and ideas too."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"A service is essentially intangible and:",a:"does not result in the ownership of anything",w:["can be stored for later sale","is always sold with a physical product","results in ownership of the provider’s equipment"],e:"Activities, benefits or satisfactions — no ownership."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"“What is the buyer really buying?” is answered at which product level?",a:"Core customer value",w:["Actual product","Augmented product","Expected product"],e:"The most basic level."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Brand name, features, design, packaging and quality level make up the:",a:"actual product",w:["core customer value","augmented product","product mix"],e:"The second level."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Warranty, after-sale service and delivery and credit belong to the:",a:"augmented product",w:["actual product","core customer value","product line"],e:"The third level."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"In what order do marketers work through the three levels when developing a product?",a:"Identify the core value, design the actual product, then find ways to augment it",w:["Augment the offer first, then design the actual product, then find the core value","All three levels at the same time, since none of them can be decided alone","Actual product first, then the core value, then the augmented product"],e:"Core → actual → augmented; each level adds customer value."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"A lawn mower bought for a landscaping business is:",a:"an industrial product",w:["a consumer product","a specialty product","an unsought product"],e:"The purpose decides — for use in conducting a business."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Consumer products are classified into convenience, shopping, specialty and unsought products according to:",a:"how consumers go about buying them",w:["how much they cost to make","who manufactures them","how long they last"],e:"The buying behavior decides the type — and the type decides how it is marketed."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Products bought frequently, immediately, with minimal comparison and effort are:",a:"convenience products",w:["shopping products","specialty products","unsought products"],e:"Convenience — candy, fast food, toothpaste."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Products the customer compares carefully on suitability, quality, price and style are:",a:"shopping products",w:["convenience products","specialty products","industrial products"],e:"Furniture, cars, appliances, phones."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Products with unique characteristics or brand identification for which buyers make a special purchase effort are:",a:"specialty products",w:["shopping products","convenience products","unsought products"],e:"Luxury watches, designer clothes, custom items — exclusive distribution, highest price."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Life insurance and blood donations are examples of:",a:"unsought products",w:["specialty products","convenience products","capital items"],e:"Unsought — they need aggressive advertising and personal selling."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Which consumer product type has exclusive distribution in only one or a few outlets per market area?",a:"Specialty",w:["Convenience","Shopping","Unsought"],e:"Specialty products."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Which consumer product type gets mass promotion by the producer?",a:"Convenience",w:["Shopping","Specialty","Unsought"],e:"Convenience products."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Which consumer product type needs aggressive advertising and personal selling?",a:"Unsought",w:["Convenience","Shopping","Specialty"],e:"Consumers do not normally think of buying them."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Which industrial product group aids in the buyer’s production or operations?",a:"Capital items",w:["Materials and parts","Supplies and services","Convenience items"],e:"Capital items — installations and accessory equipment."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Operating supplies and repair and maintenance items are the industrial world’s:",a:"convenience products",w:["specialty products","capital items","raw materials"],e:"Supplies — bought with minimal effort or comparison."},
 {tp:"c8",sec:"g8-what",t:"mc",q:"Using commercial marketing concepts to influence behavior that improves well-being is:",a:"social marketing",w:["organization marketing","internal marketing","person marketing"],e:"Social marketing."},
 {tp:"c8",sec:"g8-what",ap:true,t:"mc",q:"A financial adviser’s clients are really buying “peace of mind,” not mutual funds. Peace of mind is the product’s:",a:"core customer value",w:["actual product","augmented product","product line"],e:"What the buyer is really buying."},
 {tp:"c8",sec:"g8-what",ap:true,t:"mc",q:"A car dealer includes free car washes and a loaner car with every purchase. Which product level is it building?",a:"The augmented product",w:["The core customer value","The actual product","The product mix"],e:"Support services augment the actual product."},
 {tp:"c8",sec:"g8-what",ap:true,t:"mc",q:"A phone maker chooses the model’s name, its features and the look of its box. Which product level is it working on?",a:"The actual product",w:["The core customer value","The augmented product","The unsought product"],e:"Brand name, features, design, packaging, quality level."},
 {tp:"c8",sec:"g8-what",ap:true,t:"mc",q:"A camera bought at a pharmacy on vacation is which type of product?",a:"Convenience",w:["Specialty","Shopping","Unsought"],e:"The same camera can be shopping or specialty for other buyers — the type depends on how the buyer buys."},
 {tp:"c8",sec:"g8-what",ap:true,t:"mc",q:"A buyer visits several stores comparing sofas on price, comfort and style before choosing. A sofa is, for her, a:",a:"shopping product",w:["convenience product","specialty product","unsought product"],e:"Much planning and comparison."},
 {tp:"c8",sec:"g8-what",ap:true,t:"mc",q:"A collector will only buy one particular brand of watch and travels to the one store in the state that sells it. The watch is a:",a:"specialty product",w:["shopping product","convenience product","capital item"],e:"Strong brand preference, special purchase effort, exclusive distribution."},
 {tp:"c8",sec:"g8-what",ap:true,t:"mc",q:"A city runs a campaign to attract tourists and new businesses. This is:",a:"place marketing",w:["person marketing","organization marketing","social marketing"],e:"Cities, regions and nations compete for tourists, residents and business."},
 {tp:"c8",sec:"g8-what",ap:true,t:"mc",q:"A campaign to get drivers to stop texting at the wheel is:",a:"social marketing",w:["place marketing","organization marketing","internal marketing"],e:"Commercial marketing concepts used to improve well-being."},
 {tp:"c8",sec:"g8-what",t:"tf",q:"Broadly defined, products include experiences, organizations, persons, places and ideas.",a:true,e:"True — a product is anything offered to satisfy a need or want, so a city courting tourists and a campaign against texting while driving are both marketing products."},
 {tp:"c8",sec:"g8-what",t:"tf",q:"Each level of the product adds more customer value.",a:true,e:"True — core, actual, augmented."},
 {tp:"c8",sec:"g8-what",t:"tf",q:"Buyers normally compare specialty products carefully before buying.",a:false,e:"False — they invest only the time needed to reach the dealer carrying the wanted product."},
 {tp:"c8",sec:"g8-what",t:"tf",q:"Most major new innovations are unsought until advertising makes consumers aware of them.",a:true,e:"True — consumers cannot want what they do not know exists, which is why unsought products need aggressive advertising and personal selling."},
 {tp:"c8",sec:"g8-what",t:"tf",q:"Whether a product is a consumer or an industrial product depends on what it is, not on why it is bought.",a:false,e:"False — the purpose decides: the same mower can be either."},

 {tp:"c8",sec:"g8-decisions",t:"mc",q:"Product quality refers to:",a:"the characteristics of a product or service that bear on its ability to satisfy stated or implied customer needs",w:["the highest price a company can charge for a product before buyers begin to look elsewhere","the number of different versions of a product a company chooses to offer within one line","how widely a product is distributed and how easily buyers can find it when they want it"],e:"Narrowly it means freedom from defects; most marketers define it by customer value and satisfaction."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"A product’s ability to perform its functions is its:",a:"performance quality",w:["conformance quality","return on quality","style"],e:"Performance quality = level; conformance quality = consistency."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"Freedom from defects and consistency in delivering a targeted level of performance is:",a:"conformance quality",w:["performance quality","total quality management","design"],e:"Conformance quality — all companies should strive for it."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"Viewing quality as an investment and holding quality efforts accountable for results is:",a:"a return-on-quality approach",w:["total quality management","conformance quality","line filling"],e:"Return on quality."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"When choosing a quality level, most companies aim for:",a:"the level their target market wants, to support the product’s positioning",w:["the highest level technically possible","the lowest level the law allows","the same level as every competitor"],e:"Few companies offer the highest possible quality; they choose the level that fits the position."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"Good design begins with:",a:"observing customers, understanding their needs, and shaping their product-use experience",w:["brainstorming new ideas and making prototypes","technical product specifications","the competitor’s design"],e:"Not brainstorming and prototypes."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"Which is the larger concept — style or design?",a:"Design — it adds usefulness, not just looks",w:["Style — it adds usefulness","They are the same","Neither; packaging is larger"],e:"Design contributes to usefulness as well as looks."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"How should a company decide which features to add to a product?",a:"Compare each feature’s value to the customer with its cost to the company",w:["Add every feature customers mention","Copy the competitor’s feature list","Add only features that cost nothing"],e:"Features customers value highly relative to cost are added; the rest are dropped."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"For the buyer, a brand mainly:",a:"identifies the product and signals its quality and consistency",w:["lowers the price, because a known name is cheaper to make and to sell","guarantees a refund if the product fails to perform as it was promised","replaces the need for packaging, since the name already protects the goods"],e:"Buyers who always buy the same brand know they will get the same features and quality."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"A product line is too long if:",a:"the manager can increase profits by dropping items",w:["the manager can increase profits by adding items","it has more than ten items","it is sold in only one outlet"],e:"Too short if adding items raises profits; too long if dropping them does."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"The number of different product lines a company carries is its product mix:",a:"width",w:["length","depth","consistency"],e:"Width = lines; length = total items; depth = versions; consistency = relatedness."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"The number of versions offered of each product in a line is the mix’s:",a:"depth",w:["width","length","consistency"],e:"Depth."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"How closely a company’s product lines are related in end use, production or distribution is the mix’s:",a:"consistency",w:["width","depth","length"],e:"Consistency."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"Adding new items within a line’s present range so there are no gaps for competitors is:",a:"line filling",w:["line stretching","brand extension","multibranding"],e:"Line filling — within the current range; stretching goes beyond it."},
 {tp:"c8",sec:"g8-decisions",t:"mc",q:"Lengthening a product line beyond its current range — downward, upward or both — is:",a:"line stretching",w:["line filling","line pruning","mix consistency"],e:"Stretching reaches new price points; filling plugs gaps inside the range."},
 {tp:"c8",sec:"g8-decisions",ap:true,t:"mc",q:"A luxury car maker adds a lower-priced model to reach younger buyers below its current range. This is:",a:"line stretching — downward",w:["line filling","increasing mix width","product support"],e:"Beyond the line’s current range = stretching."},
 {tp:"c8",sec:"g8-decisions",ap:true,t:"mc",q:"A car maker already sells small, medium and large sedans, then adds a mid-size model between two of them so no competitor can slip in. This is:",a:"line filling",w:["line stretching","increasing mix width","reducing mix depth"],e:"Within the present range, plugging a gap."},
 {tp:"c8",sec:"g8-decisions",ap:true,t:"mc",q:"A coffee chain adds tumblers and brewing equipment to its coffee and food lines. Which mix dimension grows?",a:"Width",w:["Depth","Consistency","Conformance"],e:"More product lines = width."},
 {tp:"c8",sec:"g8-decisions",ap:true,t:"mc",q:"A coffee chain adds oat-milk and decaf versions of every latte. Which mix dimension grows?",a:"Depth",w:["Width","Consistency","Performance quality"],e:"More versions of each product = depth."},
 {tp:"c8",sec:"g8-decisions",ap:true,t:"mc",q:"A restaurant’s food is excellent one night and mediocre the next. Which dimension of quality is it failing?",a:"Conformance quality — consistency",w:["Performance quality — level","Return on quality","Style"],e:"It can perform, but not consistently."},
 {tp:"c8",sec:"g8-decisions",ap:true,t:"mc",q:"A shampoo maker redesigns its bottle so it stands out on a crowded shelf and is easier to grip in the shower. Which decision is that?",a:"Packaging",w:["Labeling","Line filling","Product support services"],e:"Packaging as prime marketing space — and as usefulness (design, not just style)."},
 {tp:"c8",sec:"g8-decisions",ap:true,t:"mc",q:"A car maker promises to treat every customer “as a guest in our home” and backs it with after-sale service. Which product decision is it competing on?",a:"Product support services",w:["Packaging","Labeling","Line stretching"],e:"Support services augment the actual product and keep customers after the sale."},
 {tp:"c8",sec:"g8-decisions",ap:true,t:"mc",q:"A speaker looks striking but is no easier to use than any other. It has good:",a:"style, but not necessarily good design",w:["design, but not style","conformance quality","line depth"],e:"Style is appearance; design adds usefulness."},
 {tp:"c8",sec:"g8-decisions",t:"tf",q:"Packaging’s only function today is to hold and protect the product.",a:false,e:"False — it is now prime marketing space."},
 {tp:"c8",sec:"g8-decisions",t:"tf",q:"Being the first to introduce a valued new feature is one of the most effective ways to compete.",a:true,e:"True — features are a competitive tool, and the first mover gets the advantage. The test for any feature is its value to the customer against its cost to the company."},
 {tp:"c8",sec:"g8-decisions",t:"tf",q:"Product mix length is the number of product lines the company carries.",a:false,e:"False — that is width; length is the total number of items."},
 {tp:"c8",sec:"g8-decisions",t:"tf",q:"Every company should aim for the highest possible performance quality.",a:false,e:"False — they aim for the level their target market wants; consistency (conformance) is what every company should pursue."},

 {tp:"c8",sec:"g8-services",t:"mc",q:"Services cannot be stored for later sale or use. This is:",a:"perishability",w:["intangibility","inseparability","variability"],e:"Perishability."},
 {tp:"c8",sec:"g8-services",t:"mc",q:"Services cannot be separated from their providers. This is:",a:"inseparability",w:["variability","perishability","intangibility"],e:"Inseparability."},
 {tp:"c8",sec:"g8-services",t:"mc",q:"Service quality depends on who provides it and when, where and how. This is:",a:"variability",w:["intangibility","inseparability","perishability"],e:"Variability."},
 {tp:"c8",sec:"g8-services",t:"mc",q:"Because services are intangible, buyers tend to:",a:"look for signals of quality — the place, people, equipment and price",w:["ignore quality entirely","buy only the cheapest service","store the service for later"],e:"They cannot inspect the service beforehand, so they read the evidence around it."},
 {tp:"c8",sec:"g8-services",t:"mc",q:"The service-profit chain begins with:",a:"internal service quality",w:["satisfied and loyal customers","healthy profits","external advertising"],e:"Internal service quality → satisfied employees → service value → loyal customers → profits."},
 {tp:"c8",sec:"g8-services",t:"mc",q:"The logic of the service-profit chain is that:",a:"profits start with taking care of the employees who take care of customers",w:["advertising creates service quality","profits come before employee satisfaction","customers create the service on their own"],e:"Employee satisfaction leads to service value, then to customer loyalty, then to profit."},
 {tp:"c8",sec:"g8-services",t:"mc",q:"Which must precede external marketing in a service firm?",a:"Internal marketing",w:["Interactive marketing","Line filling","Co-branding"],e:"Internal marketing — it makes no sense to advertise excellent service before the staff is ready to provide it."},
 {tp:"c8",sec:"g8-services",t:"mc",q:"Service quality depending heavily on the buyer–seller interaction during the encounter is:",a:"interactive marketing",w:["internal marketing","social marketing","organization marketing"],e:"Interactive marketing — the provider’s skill and manner are the marketing."},
 {tp:"c8",sec:"g8-services",t:"mc",q:"Perhaps the best measure of service quality is:",a:"customer retention",w:["advertising spending","number of employees","price"],e:"Customers stay with a service that meets their expectations."},
 {tp:"c8",sec:"g8-services",ap:true,t:"mc",q:"A haircut cannot be sampled before it is bought. Which service characteristic is that?",a:"Intangibility",w:["Perishability","Variability","Inseparability"],e:"Cannot be seen, tasted, felt, heard or smelled before purchase."},
 {tp:"c8",sec:"g8-services",ap:true,t:"mc",q:"An empty airline seat on today’s flight cannot be sold tomorrow. Which characteristic?",a:"Perishability",w:["Intangibility","Inseparability","Variability"],e:"Cannot be stored."},
 {tp:"c8",sec:"g8-services",ap:true,t:"mc",q:"A hotel invests in three months of training so every employee treats guests the same way. It is fighting service:",a:"variability",w:["perishability","intangibility","inseparability"],e:"Quality depends on who provides it — training reduces variability."},
 {tp:"c8",sec:"g8-services",ap:true,t:"mc",q:"A consultant’s advice is produced and consumed at the same time, in the room with the client. Which characteristic?",a:"Inseparability",w:["Perishability","Intangibility","Variability"],e:"The provider — and the customer — are part of the service."},
 {tp:"c8",sec:"g8-services",ap:true,t:"mc",q:"A dental practice trains and motivates its front-desk staff to treat patients well before it runs any ads. This is:",a:"internal marketing",w:["interactive marketing","external marketing","place marketing"],e:"Orienting and motivating employees first."},
 {tp:"c8",sec:"g8-services",ap:true,t:"mc",q:"Customers judge a bank mostly by how the teller treats them at the counter. This is the domain of:",a:"interactive marketing",w:["internal marketing","external marketing","social marketing"],e:"Quality is created in the buyer–seller interaction."},
 {tp:"c8",sec:"g8-services",ap:true,t:"mc",q:"A ski resort cuts lift-ticket prices on weekdays to fill the slopes when demand is low. It is managing service:",a:"perishability",w:["variability","intangibility","inseparability"],e:"An empty lift seat is lost; pricing shifts demand to match capacity."},
 {tp:"c8",sec:"g8-services",t:"tf",q:"In services, the provider becomes the image of the service firm.",a:true,e:"True — it is nearly impossible to separate the person from the service."},
 {tp:"c8",sec:"g8-services",t:"tf",q:"Service quality is easier to define and judge than product quality.",a:false,e:"False — it is harder."},
 {tp:"c8",sec:"g8-services",t:"tf",q:"Service productivity should be raised even at the expense of service quality.",a:false,e:"False — pushing productivity too hard can reduce quality."},

 {tp:"c8",sec:"g8-brands",t:"mc",q:"The differential effect that knowing the brand name has on customer response is:",a:"brand equity",w:["brand value","brand position","brand extension"],e:"Brand equity — “top of mind.”"},
 {tp:"c8",sec:"g8-brands",t:"mc",q:"The total financial value of a brand is its:",a:"brand value",w:["brand equity","customer equity","brand personality"],e:"Brand value — valuation is the process of estimating it."},
 {tp:"c8",sec:"g8-brands",t:"mc",q:"What is the difference between brand equity and brand value?",a:"Equity is the effect of the name on customer response; value is the brand’s worth in money",w:["They are the same thing","Equity is measured in dollars; value in customer attitudes","Value applies only to services"],e:"High equity is what produces high value."},
 {tp:"c8",sec:"g8-brands",t:"mc",q:"Young &amp; Rubicam’s BrandAsset Valuator measures brand strength on:",a:"differentiation, relevance, knowledge and esteem",w:["width, length, depth and consistency","quality, features, style and design","awareness, interest, trial and adoption"],e:"The four consumer perception dimensions."},
 {tp:"c8",sec:"g8-brands",t:"mc",q:"In the BrandAsset Valuator, “relevance” means:",a:"how well consumers feel the brand meets their needs",w:["how much the brand costs","how many products carry the name","how long the brand has existed"],e:"Differentiation = stands out; relevance = meets needs; knowledge = what consumers know; esteem = how highly they regard it."},
 {tp:"c8",sec:"g8-brands",t:"mc",q:"The fundamental asset underlying brand equity is:",a:"customer equity",w:["brand value","the product mix","conformance quality"],e:"Think of the company as a portfolio of customers."},
 {tp:"c8",sec:"g8-brands",t:"mc",q:"Which is an advantage of high brand equity?",a:"More leverage in bargaining with resellers",w:["Lower conformance quality","Fewer product lines","Less need for customer equity"],e:"Awareness and loyalty, leverage with resellers, easier extensions, defense against price competition."},
 {tp:"c8",sec:"g8-brands",t:"mc",q:"A brand with high equity is better able to:",a:"defend itself against price competition",w:["ignore its customers","skip product quality","avoid all advertising"],e:"Loyal customers do not switch for a small price difference."},
 {tp:"c8",sec:"g8-brands",t:"mc",q:"Why is measuring brand value difficult?",a:"Valuation firms weigh financial performance, role in purchase decisions and brand strength differently, so their estimates disagree",w:["Brands carry no financial value of their own, so any figure a valuation firm publishes is really a guess","Only privately held companies have brands worth valuing, and they never publish the figures behind them","Consumers refuse to name the brands they buy when surveyed, so the underlying data is never reliable"],e:"Different formulas, different rankings — all agree the strongest brands are worth billions."},
 {tp:"c8",sec:"g8-brands",t:"mc",q:"A brand works as a “short-cut” for buyers because:",a:"the name tells them what to expect, so they need not evaluate the product from scratch",w:["it lowers the price the buyer has to pay compared with an unbranded product","it removes the need for a warranty, since the maker is already identified","it makes the product intangible, so the buyer judges it on feelings alone"],e:"Brands summarize perceptions and feelings about the product and its performance."},
 {tp:"c8",sec:"g8-brands",ap:true,t:"mc",q:"Shoppers pay far more for a pair of shoes once a well-known name is on them. Which concept explains that?",a:"Brand equity",w:["Conformance quality","Line stretching","Perishability"],e:"The differential effect of knowing the brand name."},
 {tp:"c8",sec:"g8-brands",ap:true,t:"mc",q:"Asked to name a brand of tissues, most people say the same one first. That brand has:",a:"high brand equity — it is top of mind",w:["high mix consistency","low customer equity","a narrow product line"],e:"The first brand customers think of."},
 {tp:"c8",sec:"g8-brands",ap:true,t:"mc",q:"A company wants to put a dollar figure on its brand so it can list it as an asset in a sale. It needs an estimate of its:",a:"brand value",w:["brand equity","customer equity","conformance quality"],e:"Brand valuation — the total financial value."},
 {tp:"c8",sec:"g8-brands",ap:true,t:"mc",q:"A retailer gives a strong brand better shelf space because shoppers ask for it by name. The brand is enjoying which advantage of high equity?",a:"Leverage in bargaining with resellers",w:["Lower production costs","Exemption from price competition","A longer product line"],e:"Resellers want brands customers demand."},
 {tp:"c8",sec:"g8-brands",ap:true,t:"mc",q:"A company says its most valuable asset is not the brand itself but the loyal customers who buy it year after year. It is describing:",a:"customer equity",w:["brand value","product mix width","service variability"],e:"The value of the customer relationships the brand creates."},
 {tp:"c8",sec:"g8-brands",t:"tf",q:"Companies should think of themselves as portfolios of brands rather than portfolios of customers.",a:false,e:"False — the reverse; customer equity is the fundamental asset."},
 {tp:"c8",sec:"g8-brands",t:"tf",q:"A brand has positive brand equity when consumers react more favorably to it than to a generic or unbranded product.",a:true,e:"True — that difference in response is exactly what brand equity means. Negative equity is the reverse: they react less favourably once they know the name."},
 {tp:"c8",sec:"g8-brands",t:"tf",q:"Brand valuation — estimating a brand’s total financial value — is easy and exact.",a:false,e:"False — measuring it is difficult, which is why different valuation firms disagree."},
 {tp:"c8",sec:"g8-brands",t:"tf",q:"Brands exist in the minds of consumers, not just on packages.",a:true,e:"True — they represent consumers’ perceptions and feelings about the product."}
]);
